"""Offline tests for host/tools/behavior_model.py: comparison and SVG stamps.

These use no StateSmith, .NET or Java; generator output is supplied directly.
"""

from pathlib import Path
import sys
import tempfile
import unittest
import xml.dom.minidom

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "tools"))
import behavior_model as bm  # noqa: E402

C_BODY = b"// Autogenerated with StateSmith 0.22.2.\nint x;\n"
SVG_BODY = b'<svg xmlns="http://www.w3.org/2000/svg"><?plantuml 1.2026.8?><g/></svg>'
DIAGRAM = b"@startuml DemoSm\n[*] --> A\nstate A\n@enduml\n"


class BehaviorModelTests(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.repo = Path(self._tmp.name)
        (self.repo / bm.DIAGRAM_DIR).mkdir(parents=True)
        (self.repo / bm.C_DIR).mkdir(parents=True)
        self.diagram = self.repo / bm.DIAGRAM_DIR / "DemoSm.puml"
        self.diagram.write_bytes(DIAGRAM)
        self.c_files = {bm.C_DIR / "DemoSm.c": C_BODY, bm.C_DIR / "DemoSm.h": C_BODY}

    def tearDown(self):
        self._tmp.cleanup()

    def svgs(self):
        return bm.svg_sources(self.repo, bm.find_diagrams(self.repo))

    def write_current(self):
        for rel, data in self.c_files.items():
            (self.repo / rel).write_bytes(data)
        for rel, source in self.svgs().items():
            (self.repo / rel).write_bytes(bm.stamp_svg(source, SVG_BODY))

    def diffs(self):
        return [(d.kind, d.path.as_posix()) for d in bm.compare(self.c_files, self.svgs(), self.repo)]

    def test_up_to_date_tree_has_no_differences(self):
        self.write_current()
        self.assertEqual(self.diffs(), [])

    def test_missing_files_are_reported(self):
        self.assertEqual(self.diffs(), [
            ("missing", "CM7/App/sm/DemoSm.c"),
            ("missing", "CM7/App/sm/DemoSm.h"),
            ("missing", "docs/design/behavior/DemoSm.svg"),
        ])

    def test_hand_edited_c_differs(self):
        self.write_current()
        with open(self.repo / bm.C_DIR / "DemoSm.c", "ab") as f:
            f.write(b"// edit\n")
        self.assertEqual(self.diffs(), [("differs", "CM7/App/sm/DemoSm.c")])

    def test_diagram_edit_invalidates_svg(self):
        self.write_current()
        self.diagram.write_bytes(DIAGRAM.replace(b"state A", b"state A\nstate B"))
        self.assertEqual(self.diffs(), [("differs", "docs/design/behavior/DemoSm.svg")])

    def test_line_endings_do_not_invalidate_svg(self):
        self.write_current()
        self.diagram.write_bytes(DIAGRAM.replace(b"\n", b"\r\n"))
        self.assertEqual(self.diffs(), [])

    def test_hand_edited_svg_body_differs(self):
        self.write_current()
        svg = self.repo / bm.DIAGRAM_DIR / "DemoSm.svg"
        svg.write_bytes(svg.read_bytes().replace(b"<g/>", b"<g></g>"))
        self.assertEqual(self.diffs(), [("differs", "docs/design/behavior/DemoSm.svg")])

    def test_svg_from_other_plantuml_version_differs(self):
        self.write_current()
        svg = self.repo / bm.DIAGRAM_DIR / "DemoSm.svg"
        svg.write_bytes(svg.read_bytes().replace(
            f"plantuml={bm.PLANTUML_VERSION}".encode(), b"plantuml=1.2020.1"))
        self.assertEqual(self.diffs(), [("differs", "docs/design/behavior/DemoSm.svg")])

    def test_unstamped_svg_differs(self):
        self.write_current()
        (self.repo / bm.DIAGRAM_DIR / "DemoSm.svg").write_bytes(SVG_BODY)
        self.assertEqual(self.diffs(), [("differs", "docs/design/behavior/DemoSm.svg")])

    def test_generated_files_without_a_diagram_are_stale(self):
        self.write_current()
        (self.repo / bm.C_DIR / "OldSm.h").write_bytes(C_BODY)
        old = bm.SvgSource(self.repo / bm.DIAGRAM_DIR / "OldSm.puml", "0" * 64)
        (self.repo / bm.DIAGRAM_DIR / "OldSm.svg").write_bytes(bm.stamp_svg(old, SVG_BODY))
        self.assertEqual(self.diffs(), [
            ("stale", "CM7/App/sm/OldSm.h"),
            ("stale", "docs/design/behavior/OldSm.svg"),
        ])

    def test_hand_written_files_are_never_stale(self):
        self.write_current()
        (self.repo / bm.C_DIR / "demo_port.h").write_bytes(b"#ifndef DEMO_PORT_H\n")
        (self.repo / bm.C_DIR / "demo_port.c").write_bytes(b"/* mentions // Autogenerated with StateSmith */\n")
        (self.repo / bm.DIAGRAM_DIR / "figure.svg").write_bytes(SVG_BODY)
        self.assertEqual(self.diffs(), [])

    def test_stamped_svg_is_well_formed_xml(self):
        source = self.svgs()[bm.DIAGRAM_DIR / "DemoSm.svg"]
        stamped = bm.stamp_svg(source, SVG_BODY.replace(b"><", b">\r\n<"))
        self.assertNotIn(b"\r", stamped)
        self.assertEqual(xml.dom.minidom.parseString(stamped).documentElement.tagName, "svg")
        self.assertTrue(bm.svg_is_current(stamped, source))


if __name__ == "__main__":
    unittest.main()
