#!/usr/bin/env python3
"""Regenerate or check the StateSmith behavior model (decision 0006).

Every docs/design/behavior/<Name>Sm.puml diagram is the source of one state
machine. This script generates its C into CM7/App/sm/ with the StateSmith CLI
pinned in .config/dotnet-tools.json, and renders docs/design/behavior/<Name>Sm.svg
with the PlantUML jar pinned below, using the smetana layout so Java is the only
rendering dependency. Generated files are written with LF line endings.

    python host/tools/behavior_model.py            # regenerate what is out of date
    python host/tools/behavior_model.py --check    # fail if committed files are stale

Generated C is compared byte for byte; StateSmith output is the same on Windows
and Linux. SVG layout depends on the fonts Java finds, which differ between
platforms, so each SVG starts with a stamp line recording the SHA-256 of its
diagram, the PlantUML version and the SHA-256 of the rendered body. The check
verifies the stamp against the current diagram and the file's own body, so it
needs no Java, and regeneration re-renders an SVG only when its stamp is out of
date. Generated files whose diagram no longer exists are stale; --check reports
them and regeneration deletes them. --check never writes to the tree. The
firmware and host-test CMake builds never run this script.

Prerequisites: a .NET SDK (8 or later; DOTNET_ROOT set or `dotnet` on PATH) and,
to render SVG, a Java runtime (tested with 21; JAVA_HOME set or `java` on PATH). The PlantUML
jar is downloaded once into build/tools/ and verified against its SHA-256.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import re
import shlex
import shutil
import subprocess
import sys
import tempfile
import urllib.request
from dataclasses import dataclass
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
DIAGRAM_DIR = Path("docs/design/behavior")
C_DIR = Path("CM7/App/sm")
DIAGRAM_GLOB = "*Sm.puml"

PLANTUML_VERSION = "1.2026.8"
PLANTUML_URL = (
    "https://github.com/plantuml/plantuml/releases/download/"
    f"v{PLANTUML_VERSION}/plantuml-{PLANTUML_VERSION}.jar"
)
PLANTUML_SHA256 = "5e1ecfa8ecd32c90b03bbf3b1eb6f020943f98ab0fcf4032be31a0002ee2c462"
PLANTUML_CACHE = Path("build/tools") / f"plantuml-{PLANTUML_VERSION}.jar"

# Markers that identify generated files, so stale ones can be found.
C_MARKER = b"// Autogenerated with StateSmith"
SVG_STAMP_PREFIX = b"<!-- behavior_model.py "
SVG_STAMP = re.compile(
    rb"<!-- behavior_model\.py source=(?P<source>\S+) source-sha256=(?P<source_sha>[0-9a-f]{64}) "
    rb"plantuml=(?P<plantuml>\S+) svg-sha256=(?P<body_sha>[0-9a-f]{64}) -->\n"
)


class ToolError(RuntimeError):
    """A prerequisite is missing or a generator failed."""


@dataclass(frozen=True)
class Difference:
    path: Path  # repository-relative
    kind: str  # "missing", "differs" or "stale"

    def __str__(self) -> str:
        return f"{self.kind:8} {self.path.as_posix()}"


@dataclass(frozen=True)
class SvgSource:
    diagram: Path  # absolute
    sha256: str  # of the LF-normalized diagram


def normalize(data: bytes) -> bytes:
    """Use LF line endings, as .gitattributes does for the working tree."""
    return data.replace(b"\r\n", b"\n")


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def find_diagrams(repo: Path) -> list[Path]:
    return sorted((repo / DIAGRAM_DIR).glob(DIAGRAM_GLOB))


def svg_sources(repo: Path, diagrams: list[Path]) -> dict[Path, SvgSource]:
    return {
        DIAGRAM_DIR / f"{d.stem}.svg": SvgSource(d, sha256(normalize(d.read_bytes())))
        for d in diagrams
    }


def stamp_svg(source: SvgSource, body: bytes) -> bytes:
    body = normalize(body)
    stamp = (
        f"<!-- behavior_model.py source={source.diagram.name} source-sha256={source.sha256} "
        f"plantuml={PLANTUML_VERSION} svg-sha256={sha256(body)} -->\n"
    )
    return stamp.encode("ascii") + body


def svg_is_current(data: bytes, source: SvgSource) -> bool:
    """True when the SVG was rendered from this diagram and not edited since."""
    match = SVG_STAMP.match(data)
    return bool(
        match
        and match["source"].decode() == source.diagram.name
        and match["source_sha"].decode() == source.sha256
        and match["plantuml"].decode() == PLANTUML_VERSION
        and match["body_sha"].decode() == sha256(data[match.end():])
    )


def existing_generated(repo: Path) -> set[Path]:
    """Files in the tree that carry a generator marker, relative to the repo."""
    found: set[Path] = set()
    for folder, patterns, marker in (
        (C_DIR, ("*.c", "*.h"), C_MARKER),
        (DIAGRAM_DIR, ("*.svg",), SVG_STAMP_PREFIX),
    ):
        for pattern in patterns:
            for path in (repo / folder).glob(pattern):
                if path.read_bytes()[:512].startswith(marker):
                    found.add(path.relative_to(repo))
    return found


def compare(c_files: dict[Path, bytes], svgs: dict[Path, SvgSource], repo: Path) -> list[Difference]:
    """How the tree differs from what the diagrams generate."""
    diffs: list[Difference] = []
    for rel in sorted({*c_files, *svgs}):
        path = repo / rel
        if not path.exists():
            diffs.append(Difference(rel, "missing"))
            continue
        data = path.read_bytes()
        current = data == c_files[rel] if rel in c_files else svg_is_current(data, svgs[rel])
        if not current:
            diffs.append(Difference(rel, "differs"))
    for rel in sorted(existing_generated(repo) - {*c_files, *svgs}):
        diffs.append(Difference(rel, "stale"))
    return diffs


# --- Tool invocation --------------------------------------------------------


def _run(cmd: list[str], cwd: Path, env: dict[str, str] | None = None,
         terminal: bool = False) -> str:
    if terminal and sys.platform != "win32" and shutil.which("script"):
        # StateSmith.Cli has been seen to print nothing without a terminal on
        # Linux; a pseudo-terminal costs nothing where it is not needed.
        cmd = ["script", "-qefc", shlex.join(cmd), "/dev/null"]
    proc = subprocess.run(
        cmd, cwd=cwd, env=env, stdin=subprocess.DEVNULL,
        stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
    )
    out = proc.stdout.decode("utf-8", "replace")
    if proc.returncode != 0:
        raise ToolError(f"command failed ({proc.returncode}): {' '.join(cmd)}\n{out}")
    return out


def dotnet_command() -> tuple[str, dict[str, str]]:
    """The dotnet executable (DOTNET_ROOT first, then PATH) and its environment."""
    env = dict(os.environ)
    env.setdefault("DOTNET_CLI_TELEMETRY_OPTOUT", "1")
    env.setdefault("DOTNET_NOLOGO", "1")
    root = env.get("DOTNET_ROOT")
    found = (shutil.which("dotnet", path=root) if root else None) or shutil.which("dotnet")
    if not found:
        raise ToolError("dotnet not found. Install the .NET 8 SDK and set DOTNET_ROOT or PATH.")
    return found, env


def java_command() -> str:
    home = os.environ.get("JAVA_HOME")
    found = (shutil.which("java", path=str(Path(home) / "bin")) if home else None) or shutil.which("java")
    if not found:
        raise ToolError("java not found. Install a Java runtime and set JAVA_HOME or PATH.")
    return found


def plantuml_jar(repo: Path) -> Path:
    jar = repo / PLANTUML_CACHE
    if not jar.exists():
        jar.parent.mkdir(parents=True, exist_ok=True)
        print(f"downloading PlantUML {PLANTUML_VERSION}", file=sys.stderr)
        partial = jar.with_suffix(".part")
        with urllib.request.urlopen(PLANTUML_URL, timeout=120) as response:
            partial.write_bytes(response.read())
        partial.replace(jar)
    digest = sha256(jar.read_bytes())
    if digest != PLANTUML_SHA256:
        raise ToolError(f"{jar} has SHA-256 {digest}, expected {PLANTUML_SHA256}; delete it and rerun")
    return jar


def generate_c(repo: Path, diagrams: list[Path]) -> dict[Path, bytes]:
    """Run StateSmith on copies of the diagrams; return the C keyed by destination."""
    if not diagrams:
        return {}
    dotnet, env = dotnet_command()
    _run([dotnet, "tool", "restore"], repo, env)
    generated: dict[Path, bytes] = {}
    with tempfile.TemporaryDirectory(prefix="behavior-model-") as tmp:
        for diagram in diagrams:
            name = diagram.stem
            work = Path(tmp) / name
            work.mkdir()
            source = work / diagram.name
            shutil.copyfile(diagram, source)
            log = _run(
                [dotnet, "tool", "run", "ss.cli", "--", "run", "--lang", "C99",
                 "--no-sim-gen", "--no-ask", "--rebuild", str(source)],
                repo, env, terminal=True,
            )
            produced = sorted(p.name for p in work.iterdir() if p != source)
            if not produced:
                # StateSmith reports diagram errors but still exits with status 0.
                raise ToolError(f"{diagram.name}: StateSmith generated nothing.\n{log}")
            if produced != [f"{name}.c", f"{name}.h"]:
                raise ToolError(
                    f"{diagram.name}: expected {name}.c and {name}.h, StateSmith produced {produced}. "
                    "The @startuml name must match the file name, and the diagram must not "
                    "set outputDirectory."
                )
            for filename in produced:
                generated[C_DIR / filename] = normalize((work / filename).read_bytes())
    return generated


def render_svg(repo: Path, source: SvgSource) -> bytes:
    java = java_command()
    jar = plantuml_jar(repo)
    with tempfile.TemporaryDirectory(prefix="behavior-model-svg-") as tmp:
        copy = Path(tmp) / source.diagram.name
        shutil.copyfile(source.diagram, copy)
        out = Path(tmp) / "out"
        _run([java, "-Djava.awt.headless=true", "-jar", str(jar), "-tsvg", "-Playout=smetana",
              "-failfast2", "-o", str(out), str(copy)], repo)
        rendered = out / f"{source.diagram.stem}.svg"
        if not rendered.exists():
            raise ToolError(f"{source.diagram.name}: PlantUML did not write {rendered.name}")
        return stamp_svg(source, rendered.read_bytes())


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="fail if committed generated files differ from a fresh generation")
    args = parser.parse_args(argv)

    diagrams = find_diagrams(REPO)
    try:
        c_files = generate_c(REPO, diagrams)
        svgs = svg_sources(REPO, diagrams)
        diffs = compare(c_files, svgs, REPO)
        if args.check:
            for diff in diffs:
                print(diff)
            if diffs:
                print(f"behavior model out of date: {len(diffs)} file(s); run "
                      "python host/tools/behavior_model.py", file=sys.stderr)
                return 1
            print(f"behavior model up to date ({len(diagrams)} diagram(s))")
            return 0
        for diff in diffs:
            path = REPO / diff.path
            if diff.kind == "stale":
                path.unlink()
            else:
                data = c_files[diff.path] if diff.path in c_files else render_svg(REPO, svgs[diff.path])
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_bytes(data)
            print(diff)
    except ToolError as error:
        print(f"error: {error}", file=sys.stderr)
        return 2
    print(f"behavior model regenerated ({len(diagrams)} diagram(s), {len(diffs)} file(s) changed)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
