// Autogenerated with StateSmith 0.22.2+0c32be37bf4d4fee5499780a5ef37a7996c192f9.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

#include "ContextSm.h"
#include <stdbool.h> // required for `consume_event` flag
#include <string.h> // for memset
#include "context_port.h"


// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(ContextSm* sm, ContextSm_StateId desired_state);

static void ROOT_enter(ContextSm* sm);

static void RUNNING_enter(ContextSm* sm);

static void RUNNING_exit(ContextSm* sm);

static void RUNNING_ptt_off(ContextSm* sm);

static void RUNNING_reconcile(ContextSm* sm);

static void Running_ChoicePoint_UtilityResume__transition(ContextSm* sm);

static void FIELD_enter(ContextSm* sm);

static void FIELD_exit(ContextSm* sm);

static void FIELD_ptt_on(ContextSm* sm);

static void Field_ChoicePoint_FieldResume__transition(ContextSm* sm);

static void FIELDPAGE_enter(ContextSm* sm);

static void FIELDPAGE_exit(ContextSm* sm);

static void FIELDPAGE_e1_hold(ContextSm* sm);

static void FIELDPAGE_e2_hold(ContextSm* sm);

static void FIELDPAGE_e3_click(ContextSm* sm);

static void FIELDPAGE_shift_b0(ContextSm* sm);

static void FIELDPAGE_shift_b1(ContextSm* sm);

static void FIELDPAGE_shift_chord(ContextSm* sm);

static void FIELDPAGE_shift_e0(ContextSm* sm);

static void CLASSIC_enter(ContextSm* sm);

static void CLASSIC_exit(ContextSm* sm);

static void CLASSIC_e0_click(ContextSm* sm);

static void CLASSIC_e0_turn(ContextSm* sm);

static void CLASSIC_e1_click(ContextSm* sm);

static void CLASSIC_e1_turn(ContextSm* sm);

static void CLASSIC_shift_e1(ContextSm* sm);

static void MANUAL_enter(ContextSm* sm);

static void MANUAL_exit(ContextSm* sm);

static void MANUAL_e0_click(ContextSm* sm);

static void MANUAL_e0_turn(ContextSm* sm);

static void MANUALDIRECT_enter(ContextSm* sm);

static void MANUALDIRECT_exit(ContextSm* sm);

static void MANUALQUICKJUMP_enter(ContextSm* sm);

static void MANUALQUICKJUMP_exit(ContextSm* sm);

static void MANUALQUICKJUMP_shift_e1(ContextSm* sm);

static void MENU_enter(ContextSm* sm);

static void MENU_exit(ContextSm* sm);

static void MENU_e0_turn(ContextSm* sm);

static void MENU_e1_click(ContextSm* sm);

static void MENU_menu_timeout(ContextSm* sm);

static void MENU_reconcile(ContextSm* sm);

static void BANDMENU_enter(ContextSm* sm);

static void BANDMENU_exit(ContextSm* sm);

static void BANDMENU_e0_click(ContextSm* sm);

static void BANDMENU_session_changed(ContextSm* sm);

static void ENGINEMENU_enter(ContextSm* sm);

static void ENGINEMENU_exit(ContextSm* sm);

static void ENGINEMENU_e0_click(ContextSm* sm);

static void INSTRUMENT_enter(ContextSm* sm);

static void INSTRUMENT_exit(ContextSm* sm);

static void INSTRUMENT_shift_b0(ContextSm* sm);

static void INSTRUMENT_shift_e0(ContextSm* sm);

static void UTILITY_enter(ContextSm* sm);

static void UTILITY_exit(ContextSm* sm);

static void UTILITY_e0_click(ContextSm* sm);

static void UTILITY_e0_turn(ContextSm* sm);

static void UTILITY_e1_click(ContextSm* sm);

static void UTILITY_e3_hold(ContextSm* sm);


// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void ContextSm_ctor(ContextSm* sm)
{
    memset(sm, 0, sizeof(*sm));
}

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void ContextSm_start(ContextSm* sm)
{
    ROOT_enter(sm);
    // ROOT behavior
    // uml: TransitionTo(ROOT.<InitialState>)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `ROOT.<InitialState>`.
        // ROOT.<InitialState> is a pseudo state and cannot have an `enter` trigger.
        
        // ROOT.<InitialState> behavior
        // uml: TransitionTo(Running)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `Running`.
            RUNNING_enter(sm);
            
            // Running.<InitialState> behavior
            // uml: TransitionTo(Field)
            {
                // Step 1: Exit states until we reach `Running` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
                
                // Step 2: Transition action: ``.
                
                // Step 3: Enter/move towards transition target `Field`.
                FIELD_enter(sm);
                
                // Field.<InitialState> behavior
                // uml: TransitionTo(FieldPage)
                {
                    // Step 1: Exit states until we reach `Field` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
                    
                    // Step 2: Transition action: ``.
                    
                    // Step 3: Enter/move towards transition target `FieldPage`.
                    FIELDPAGE_enter(sm);
                    
                    // FieldPage.<InitialState> behavior
                    // uml: TransitionTo(Classic)
                    {
                        // Step 1: Exit states until we reach `FieldPage` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
                        
                        // Step 2: Transition action: ``.
                        
                        // Step 3: Enter/move towards transition target `Classic`.
                        CLASSIC_enter(sm);
                        
                        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                        return;
                    } // end of behavior for FieldPage.<InitialState>
                } // end of behavior for Field.<InitialState>
            } // end of behavior for Running.<InitialState>
        } // end of behavior for ROOT.<InitialState>
    } // end of behavior for ROOT
}

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void ContextSm_dispatch_event(ContextSm* sm, ContextSm_EventId event_id)
{
    switch (sm->state_id)
    {
        // STATE: ContextSm
        case ContextSm_StateId_ROOT:
            // No events handled by this state (or its ancestors).
            break;
        
        // STATE: Running
        case ContextSm_StateId_RUNNING:
            switch (event_id)
            {
                case ContextSm_EventId_PTT_OFF: RUNNING_ptt_off(sm); break;
                case ContextSm_EventId_RECONCILE: RUNNING_reconcile(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: Field
        case ContextSm_StateId_FIELD:
            switch (event_id)
            {
                case ContextSm_EventId_PTT_ON: FIELD_ptt_on(sm); break;
                case ContextSm_EventId_PTT_OFF: RUNNING_ptt_off(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_RECONCILE: RUNNING_reconcile(sm); break; // First ancestor handler for this event
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: FieldPage
        case ContextSm_StateId_FIELDPAGE:
            switch (event_id)
            {
                case ContextSm_EventId_E3_CLICK: FIELDPAGE_e3_click(sm); break;
                case ContextSm_EventId_E1_HOLD: FIELDPAGE_e1_hold(sm); break;
                case ContextSm_EventId_SHIFT_B1: FIELDPAGE_shift_b1(sm); break;
                case ContextSm_EventId_SHIFT_B0: FIELDPAGE_shift_b0(sm); break;
                case ContextSm_EventId_SHIFT_CHORD: FIELDPAGE_shift_chord(sm); break;
                case ContextSm_EventId_E2_HOLD: FIELDPAGE_e2_hold(sm); break;
                case ContextSm_EventId_SHIFT_E0: FIELDPAGE_shift_e0(sm); break;
                case ContextSm_EventId_PTT_OFF: RUNNING_ptt_off(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_RECONCILE: RUNNING_reconcile(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_PTT_ON: FIELD_ptt_on(sm); break; // First ancestor handler for this event
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: Classic
        case ContextSm_StateId_CLASSIC:
            switch (event_id)
            {
                case ContextSm_EventId_E0_TURN: CLASSIC_e0_turn(sm); break;
                case ContextSm_EventId_E1_TURN: CLASSIC_e1_turn(sm); break;
                case ContextSm_EventId_E0_CLICK: CLASSIC_e0_click(sm); break;
                case ContextSm_EventId_E1_CLICK: CLASSIC_e1_click(sm); break;
                case ContextSm_EventId_SHIFT_E1: CLASSIC_shift_e1(sm); break;
                case ContextSm_EventId_PTT_OFF: RUNNING_ptt_off(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_RECONCILE: RUNNING_reconcile(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_PTT_ON: FIELD_ptt_on(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_E3_CLICK: FIELDPAGE_e3_click(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_E1_HOLD: FIELDPAGE_e1_hold(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_SHIFT_B1: FIELDPAGE_shift_b1(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_SHIFT_B0: FIELDPAGE_shift_b0(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_SHIFT_CHORD: FIELDPAGE_shift_chord(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_E2_HOLD: FIELDPAGE_e2_hold(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_SHIFT_E0: FIELDPAGE_shift_e0(sm); break; // First ancestor handler for this event
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: Manual
        case ContextSm_StateId_MANUAL:
            switch (event_id)
            {
                case ContextSm_EventId_E0_TURN: MANUAL_e0_turn(sm); break;
                case ContextSm_EventId_E0_CLICK: MANUAL_e0_click(sm); break;
                case ContextSm_EventId_PTT_OFF: RUNNING_ptt_off(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_RECONCILE: RUNNING_reconcile(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_PTT_ON: FIELD_ptt_on(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_E3_CLICK: FIELDPAGE_e3_click(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_E1_HOLD: FIELDPAGE_e1_hold(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_SHIFT_B1: FIELDPAGE_shift_b1(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_SHIFT_B0: FIELDPAGE_shift_b0(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_SHIFT_CHORD: FIELDPAGE_shift_chord(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_E2_HOLD: FIELDPAGE_e2_hold(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_SHIFT_E0: FIELDPAGE_shift_e0(sm); break; // First ancestor handler for this event
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: ManualDirect
        case ContextSm_StateId_MANUALDIRECT:
            switch (event_id)
            {
                case ContextSm_EventId_PTT_OFF: RUNNING_ptt_off(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_RECONCILE: RUNNING_reconcile(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_PTT_ON: FIELD_ptt_on(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_E3_CLICK: FIELDPAGE_e3_click(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_E1_HOLD: FIELDPAGE_e1_hold(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_SHIFT_B1: FIELDPAGE_shift_b1(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_SHIFT_B0: FIELDPAGE_shift_b0(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_SHIFT_CHORD: FIELDPAGE_shift_chord(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_E2_HOLD: FIELDPAGE_e2_hold(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_SHIFT_E0: FIELDPAGE_shift_e0(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_E0_TURN: MANUAL_e0_turn(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_E0_CLICK: MANUAL_e0_click(sm); break; // First ancestor handler for this event
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: ManualQuickJump
        case ContextSm_StateId_MANUALQUICKJUMP:
            switch (event_id)
            {
                case ContextSm_EventId_SHIFT_E1: MANUALQUICKJUMP_shift_e1(sm); break;
                case ContextSm_EventId_PTT_OFF: RUNNING_ptt_off(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_RECONCILE: RUNNING_reconcile(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_PTT_ON: FIELD_ptt_on(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_E3_CLICK: FIELDPAGE_e3_click(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_E1_HOLD: FIELDPAGE_e1_hold(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_SHIFT_B1: FIELDPAGE_shift_b1(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_SHIFT_B0: FIELDPAGE_shift_b0(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_SHIFT_CHORD: FIELDPAGE_shift_chord(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_E2_HOLD: FIELDPAGE_e2_hold(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_SHIFT_E0: FIELDPAGE_shift_e0(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_E0_TURN: MANUAL_e0_turn(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_E0_CLICK: MANUAL_e0_click(sm); break; // First ancestor handler for this event
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: Menu
        case ContextSm_StateId_MENU:
            switch (event_id)
            {
                case ContextSm_EventId_E0_TURN: MENU_e0_turn(sm); break;
                case ContextSm_EventId_E1_CLICK: MENU_e1_click(sm); break;
                case ContextSm_EventId_MENU_TIMEOUT: MENU_menu_timeout(sm); break;
                case ContextSm_EventId_RECONCILE: MENU_reconcile(sm); break;
                case ContextSm_EventId_PTT_OFF: RUNNING_ptt_off(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_PTT_ON: FIELD_ptt_on(sm); break; // First ancestor handler for this event
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: BandMenu
        case ContextSm_StateId_BANDMENU:
            switch (event_id)
            {
                case ContextSm_EventId_E0_CLICK: BANDMENU_e0_click(sm); break;
                case ContextSm_EventId_SESSION_CHANGED: BANDMENU_session_changed(sm); break;
                case ContextSm_EventId_PTT_OFF: RUNNING_ptt_off(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_RECONCILE: MENU_reconcile(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_PTT_ON: FIELD_ptt_on(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_E0_TURN: MENU_e0_turn(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_E1_CLICK: MENU_e1_click(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_MENU_TIMEOUT: MENU_menu_timeout(sm); break; // First ancestor handler for this event
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: EngineMenu
        case ContextSm_StateId_ENGINEMENU:
            switch (event_id)
            {
                case ContextSm_EventId_E0_CLICK: ENGINEMENU_e0_click(sm); break;
                case ContextSm_EventId_PTT_OFF: RUNNING_ptt_off(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_RECONCILE: MENU_reconcile(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_PTT_ON: FIELD_ptt_on(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_E0_TURN: MENU_e0_turn(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_E1_CLICK: MENU_e1_click(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_MENU_TIMEOUT: MENU_menu_timeout(sm); break; // First ancestor handler for this event
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: Instrument
        case ContextSm_StateId_INSTRUMENT:
            switch (event_id)
            {
                case ContextSm_EventId_SHIFT_B0: INSTRUMENT_shift_b0(sm); break;
                case ContextSm_EventId_SHIFT_E0: INSTRUMENT_shift_e0(sm); break;
                case ContextSm_EventId_PTT_OFF: RUNNING_ptt_off(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_RECONCILE: RUNNING_reconcile(sm); break; // First ancestor handler for this event
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: Utility
        case ContextSm_StateId_UTILITY:
            switch (event_id)
            {
                case ContextSm_EventId_E0_TURN: UTILITY_e0_turn(sm); break;
                case ContextSm_EventId_E0_CLICK: UTILITY_e0_click(sm); break;
                case ContextSm_EventId_E1_CLICK: UTILITY_e1_click(sm); break;
                case ContextSm_EventId_E3_HOLD: UTILITY_e3_hold(sm); break;
                case ContextSm_EventId_PTT_OFF: RUNNING_ptt_off(sm); break; // First ancestor handler for this event
                case ContextSm_EventId_RECONCILE: RUNNING_reconcile(sm); break; // First ancestor handler for this event
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
    }
    
}

// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(ContextSm* sm, ContextSm_StateId desired_state)
{
    while (sm->state_id != desired_state)
    {
        switch (sm->state_id)
        {
            case ContextSm_StateId_RUNNING: RUNNING_exit(sm); break;
            
            case ContextSm_StateId_FIELD: FIELD_exit(sm); break;
            
            case ContextSm_StateId_FIELDPAGE: FIELDPAGE_exit(sm); break;
            
            case ContextSm_StateId_CLASSIC: CLASSIC_exit(sm); break;
            
            case ContextSm_StateId_MANUAL: MANUAL_exit(sm); break;
            
            case ContextSm_StateId_MANUALDIRECT: MANUALDIRECT_exit(sm); break;
            
            case ContextSm_StateId_MANUALQUICKJUMP: MANUALQUICKJUMP_exit(sm); break;
            
            case ContextSm_StateId_MENU: MENU_exit(sm); break;
            
            case ContextSm_StateId_BANDMENU: BANDMENU_exit(sm); break;
            
            case ContextSm_StateId_ENGINEMENU: ENGINEMENU_exit(sm); break;
            
            case ContextSm_StateId_INSTRUMENT: INSTRUMENT_exit(sm); break;
            
            case ContextSm_StateId_UTILITY: UTILITY_exit(sm); break;
            
            default: return;  // Just to be safe. Prevents infinite loop if state ID memory is somehow corrupted.
        }
    }
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state ROOT
////////////////////////////////////////////////////////////////////////////////

static void ROOT_enter(ContextSm* sm)
{
    sm->state_id = ContextSm_StateId_ROOT;
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state RUNNING
////////////////////////////////////////////////////////////////////////////////

static void RUNNING_enter(ContextSm* sm)
{
    sm->state_id = ContextSm_StateId_RUNNING;
}

static void RUNNING_exit(ContextSm* sm)
{
    sm->state_id = ContextSm_StateId_ROOT;
}

static void RUNNING_ptt_off(ContextSm* sm)
{
    // Running behavior
    // uml: PTT_OFF / { ctx_ptt_off(); }
    {
        // Step 1: execute action `ctx_ptt_off();`
        ctx_ptt_off();
    } // end of behavior for Running
    
    // No ancestor handles this event.
}

static void RUNNING_reconcile(ContextSm* sm)
{
    // Running behavior
    // uml: RECONCILE / { ctx_ptt_off(); }
    {
        // Step 1: execute action `ctx_ptt_off();`
        ctx_ptt_off();
    } // end of behavior for Running
    
    // No ancestor handles this event.
}

static void Running_ChoicePoint_UtilityResume__transition(ContextSm* sm)
{
    // Running.<ChoicePoint>(UtilityResume) behavior
    // uml: [ctx_current_page_is(CTX_PAGE_INSTRUMENT)] TransitionTo(Instrument)
    if (ctx_current_page_is(CTX_PAGE_INSTRUMENT))
    {
        // Step 1: Exit states until we reach `Running` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `Instrument`.
        INSTRUMENT_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for Running.<ChoicePoint>(UtilityResume)
    
    // Running.<ChoicePoint>(UtilityResume) behavior
    // uml: TransitionTo(Field.<ChoicePoint>(FieldResume))
    {
        // Step 1: Exit states until we reach `Running` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `Field.<ChoicePoint>(FieldResume)`.
        FIELD_enter(sm);
        // Field.<ChoicePoint>(FieldResume) is a pseudo state and cannot have an `enter` trigger.
        
        // Finish transition by calling pseudo state transition function.
        Field_ChoicePoint_FieldResume__transition(sm);
        return; // event processing immediately stops when a transition finishes. No other behaviors for this state are checked.
    } // end of behavior for Running.<ChoicePoint>(UtilityResume)
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state FIELD
////////////////////////////////////////////////////////////////////////////////

static void FIELD_enter(ContextSm* sm)
{
    sm->state_id = ContextSm_StateId_FIELD;
}

static void FIELD_exit(ContextSm* sm)
{
    sm->state_id = ContextSm_StateId_RUNNING;
}

static void FIELD_ptt_on(ContextSm* sm)
{
    // Field behavior
    // uml: PTT_ON / { ctx_ptt_on(); }
    {
        // Step 1: execute action `ctx_ptt_on();`
        ctx_ptt_on();
    } // end of behavior for Field
    
    // No ancestor handles this event.
}

static void Field_ChoicePoint_FieldResume__transition(ContextSm* sm)
{
    // Field.<ChoicePoint>(FieldResume) behavior
    // uml: [ctx_field_page_is(CTX_PAGE_CLASSIC)] TransitionTo(Classic)
    if (ctx_field_page_is(CTX_PAGE_CLASSIC))
    {
        // Step 1: Exit states until we reach `Field` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `Classic`.
        FIELDPAGE_enter(sm);
        CLASSIC_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for Field.<ChoicePoint>(FieldResume)
    
    // Field.<ChoicePoint>(FieldResume) behavior
    // uml: [ctx_field_page_is(CTX_PAGE_MANUAL_QUICK_JUMP)] TransitionTo(ManualQuickJump)
    if (ctx_field_page_is(CTX_PAGE_MANUAL_QUICK_JUMP))
    {
        // Step 1: Exit states until we reach `Field` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `ManualQuickJump`.
        FIELDPAGE_enter(sm);
        MANUAL_enter(sm);
        MANUALQUICKJUMP_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for Field.<ChoicePoint>(FieldResume)
    
    // Field.<ChoicePoint>(FieldResume) behavior
    // uml: TransitionTo(ManualDirect)
    {
        // Step 1: Exit states until we reach `Field` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `ManualDirect`.
        FIELDPAGE_enter(sm);
        MANUAL_enter(sm);
        MANUALDIRECT_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for Field.<ChoicePoint>(FieldResume)
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state FIELDPAGE
////////////////////////////////////////////////////////////////////////////////

static void FIELDPAGE_enter(ContextSm* sm)
{
    sm->state_id = ContextSm_StateId_FIELDPAGE;
}

static void FIELDPAGE_exit(ContextSm* sm)
{
    sm->state_id = ContextSm_StateId_FIELD;
}

static void FIELDPAGE_e1_hold(ContextSm* sm)
{
    // FieldPage behavior
    // uml: E1_HOLD [!ctx_band_change_allowed()] / { ctx_reject(CTX_ACTION_BAND_CHANGE); }
    if (!ctx_band_change_allowed())
    {
        // Step 1: execute action `ctx_reject(CTX_ACTION_BAND_CHANGE);`
        ctx_reject(CTX_ACTION_BAND_CHANGE);
    } // end of behavior for FieldPage
    
    // FieldPage behavior
    // uml: E1_HOLD [ctx_band_change_allowed()] TransitionTo(BandMenu)
    if (ctx_band_change_allowed())
    {
        // Step 1: Exit states until we reach `Field` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, ContextSm_StateId_FIELD);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `BandMenu`.
        MENU_enter(sm);
        BANDMENU_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for FieldPage
    
    // No ancestor handles this event.
}

static void FIELDPAGE_e2_hold(ContextSm* sm)
{
    // FieldPage behavior
    // uml: E2_HOLD TransitionTo(EngineMenu)
    {
        // Step 1: Exit states until we reach `Field` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, ContextSm_StateId_FIELD);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `EngineMenu`.
        MENU_enter(sm);
        ENGINEMENU_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for FieldPage
    
    // No ancestor handles this event.
}

static void FIELDPAGE_e3_click(ContextSm* sm)
{
    // FieldPage behavior
    // uml: E3_CLICK / { ctx_page_advance(); }
    {
        // Step 1: execute action `ctx_page_advance();`
        ctx_page_advance();
    } // end of behavior for FieldPage
    
    // No ancestor handles this event.
}

static void FIELDPAGE_shift_b0(ContextSm* sm)
{
    // FieldPage behavior
    // uml: SHIFT_B0 [ctx_session_active()] / { ctx_reject(CTX_ACTION_MODE_SWITCH); }
    if (ctx_session_active())
    {
        // Step 1: execute action `ctx_reject(CTX_ACTION_MODE_SWITCH);`
        ctx_reject(CTX_ACTION_MODE_SWITCH);
    } // end of behavior for FieldPage
    
    // FieldPage behavior
    // uml: SHIFT_B0 [!ctx_session_active()] / { ctx_mode_changed(CTX_MODE_INSTRUMENT); } TransitionTo(Instrument)
    if (!ctx_session_active())
    {
        // Step 1: Exit states until we reach `Running` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, ContextSm_StateId_RUNNING);
        
        // Step 2: Transition action: `ctx_mode_changed(CTX_MODE_INSTRUMENT);`.
        ctx_mode_changed(CTX_MODE_INSTRUMENT);
        
        // Step 3: Enter/move towards transition target `Instrument`.
        INSTRUMENT_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for FieldPage
    
    // No ancestor handles this event.
}

static void FIELDPAGE_shift_b1(ContextSm* sm)
{
    // FieldPage behavior
    // uml: SHIFT_B1 / { ctx_command(CTX_CMD_CAPTURE_SAVE, 0); }
    {
        // Step 1: execute action `ctx_command(CTX_CMD_CAPTURE_SAVE, 0);`
        ctx_command(CTX_CMD_CAPTURE_SAVE, 0);
    } // end of behavior for FieldPage
    
    // No ancestor handles this event.
}

static void FIELDPAGE_shift_chord(ContextSm* sm)
{
    // FieldPage behavior
    // uml: SHIFT_CHORD [ctx_session_active()] / { ctx_command(CTX_CMD_CAPTURE_SAVE, 0); ctx_reject(CTX_ACTION_MODE_SWITCH); }
    if (ctx_session_active())
    {
        // Step 1: execute action `ctx_command(CTX_CMD_CAPTURE_SAVE, 0); ctx_reject(CTX_ACTION_MODE_SWITCH);`
        ctx_command(CTX_CMD_CAPTURE_SAVE, 0); ctx_reject(CTX_ACTION_MODE_SWITCH);
    } // end of behavior for FieldPage
    
    // FieldPage behavior
    // uml: SHIFT_CHORD [!ctx_session_active()] / { ctx_command(CTX_CMD_CAPTURE_SAVE, 0); ctx_command(CTX_CMD_LOAD_CAPTURE, 0); ctx_mode_changed(CTX_MODE_INSTRUMENT); } TransitionTo(Instrument)
    if (!ctx_session_active())
    {
        // Step 1: Exit states until we reach `Running` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, ContextSm_StateId_RUNNING);
        
        // Step 2: Transition action: `ctx_command(CTX_CMD_CAPTURE_SAVE, 0); ctx_command(CTX_CMD_LOAD_CAPTURE, 0); ctx_mode_changed(CTX_MODE_INSTRUMENT);`.
        ctx_command(CTX_CMD_CAPTURE_SAVE, 0); ctx_command(CTX_CMD_LOAD_CAPTURE, 0); ctx_mode_changed(CTX_MODE_INSTRUMENT);
        
        // Step 3: Enter/move towards transition target `Instrument`.
        INSTRUMENT_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for FieldPage
    
    // No ancestor handles this event.
}

static void FIELDPAGE_shift_e0(ContextSm* sm)
{
    // FieldPage behavior
    // uml: SHIFT_E0 TransitionTo(Utility)
    {
        // Step 1: Exit states until we reach `Running` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, ContextSm_StateId_RUNNING);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `Utility`.
        UTILITY_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for FieldPage
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state CLASSIC
////////////////////////////////////////////////////////////////////////////////

static void CLASSIC_enter(ContextSm* sm)
{
    sm->state_id = ContextSm_StateId_CLASSIC;
    
    // Classic behavior
    // uml: enter / { ctx_page_entered(CTX_PAGE_CLASSIC); }
    {
        // Step 1: execute action `ctx_page_entered(CTX_PAGE_CLASSIC);`
        ctx_page_entered(CTX_PAGE_CLASSIC);
    } // end of behavior for Classic
}

static void CLASSIC_exit(ContextSm* sm)
{
    sm->state_id = ContextSm_StateId_FIELDPAGE;
}

static void CLASSIC_e0_click(ContextSm* sm)
{
    // Classic behavior
    // uml: E0_CLICK / { ctx_command(CTX_CMD_RUN_PAUSE, 0); }
    {
        // Step 1: execute action `ctx_command(CTX_CMD_RUN_PAUSE, 0);`
        ctx_command(CTX_CMD_RUN_PAUSE, 0);
    } // end of behavior for Classic
    
    // No ancestor handles this event.
}

static void CLASSIC_e0_turn(ContextSm* sm)
{
    // Classic behavior
    // uml: E0_TURN / { ctx_command(CTX_CMD_JUMP_RATE, ctx_detents()); }
    {
        // Step 1: execute action `ctx_command(CTX_CMD_JUMP_RATE, ctx_detents());`
        ctx_command(CTX_CMD_JUMP_RATE, ctx_detents());
    } // end of behavior for Classic
    
    // No ancestor handles this event.
}

static void CLASSIC_e1_click(ContextSm* sm)
{
    // Classic behavior
    // uml: E1_CLICK / { ctx_command(CTX_CMD_TOGGLE_DIRECTION, 0); }
    {
        // Step 1: execute action `ctx_command(CTX_CMD_TOGGLE_DIRECTION, 0);`
        ctx_command(CTX_CMD_TOGGLE_DIRECTION, 0);
    } // end of behavior for Classic
    
    // No ancestor handles this event.
}

static void CLASSIC_e1_turn(ContextSm* sm)
{
    // Classic behavior
    // uml: E1_TURN / { ctx_command(CTX_CMD_JUMP_DISTANCE, ctx_detents()); }
    {
        // Step 1: execute action `ctx_command(CTX_CMD_JUMP_DISTANCE, ctx_detents());`
        ctx_command(CTX_CMD_JUMP_DISTANCE, ctx_detents());
    } // end of behavior for Classic
    
    // No ancestor handles this event.
}

static void CLASSIC_shift_e1(ContextSm* sm)
{
    // Classic behavior
    // uml: SHIFT_E1 / { ctx_select_engine(CTX_ENGINE_MANUAL); } TransitionTo(ManualQuickJump)
    {
        // Step 1: Exit states until we reach `FieldPage` state (Least Common Ancestor for transition).
        CLASSIC_exit(sm);
        
        // Step 2: Transition action: `ctx_select_engine(CTX_ENGINE_MANUAL);`.
        ctx_select_engine(CTX_ENGINE_MANUAL);
        
        // Step 3: Enter/move towards transition target `ManualQuickJump`.
        MANUAL_enter(sm);
        MANUALQUICKJUMP_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for Classic
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state MANUAL
////////////////////////////////////////////////////////////////////////////////

static void MANUAL_enter(ContextSm* sm)
{
    sm->state_id = ContextSm_StateId_MANUAL;
}

static void MANUAL_exit(ContextSm* sm)
{
    sm->state_id = ContextSm_StateId_FIELDPAGE;
}

static void MANUAL_e0_click(ContextSm* sm)
{
    // Manual behavior
    // uml: E0_CLICK / { ctx_command(CTX_CMD_TOGGLE_WRAP, 0); }
    {
        // Step 1: execute action `ctx_command(CTX_CMD_TOGGLE_WRAP, 0);`
        ctx_command(CTX_CMD_TOGGLE_WRAP, 0);
    } // end of behavior for Manual
    
    // No ancestor handles this event.
}

static void MANUAL_e0_turn(ContextSm* sm)
{
    // Manual behavior
    // uml: E0_TURN / { ctx_command(CTX_CMD_TUNE, ctx_detents()); }
    {
        // Step 1: execute action `ctx_command(CTX_CMD_TUNE, ctx_detents());`
        ctx_command(CTX_CMD_TUNE, ctx_detents());
    } // end of behavior for Manual
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state MANUALDIRECT
////////////////////////////////////////////////////////////////////////////////

static void MANUALDIRECT_enter(ContextSm* sm)
{
    sm->state_id = ContextSm_StateId_MANUALDIRECT;
    
    // ManualDirect behavior
    // uml: enter / { ctx_page_entered(CTX_PAGE_MANUAL); }
    {
        // Step 1: execute action `ctx_page_entered(CTX_PAGE_MANUAL);`
        ctx_page_entered(CTX_PAGE_MANUAL);
    } // end of behavior for ManualDirect
}

static void MANUALDIRECT_exit(ContextSm* sm)
{
    sm->state_id = ContextSm_StateId_MANUAL;
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state MANUALQUICKJUMP
////////////////////////////////////////////////////////////////////////////////

static void MANUALQUICKJUMP_enter(ContextSm* sm)
{
    sm->state_id = ContextSm_StateId_MANUALQUICKJUMP;
    
    // ManualQuickJump behavior
    // uml: enter / { ctx_page_entered(CTX_PAGE_MANUAL_QUICK_JUMP); }
    {
        // Step 1: execute action `ctx_page_entered(CTX_PAGE_MANUAL_QUICK_JUMP);`
        ctx_page_entered(CTX_PAGE_MANUAL_QUICK_JUMP);
    } // end of behavior for ManualQuickJump
}

static void MANUALQUICKJUMP_exit(ContextSm* sm)
{
    sm->state_id = ContextSm_StateId_MANUAL;
}

static void MANUALQUICKJUMP_shift_e1(ContextSm* sm)
{
    // ManualQuickJump behavior
    // uml: SHIFT_E1 / { ctx_select_engine(CTX_ENGINE_CLASSIC); } TransitionTo(Classic)
    {
        // Step 1: Exit states until we reach `FieldPage` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, ContextSm_StateId_FIELDPAGE);
        
        // Step 2: Transition action: `ctx_select_engine(CTX_ENGINE_CLASSIC);`.
        ctx_select_engine(CTX_ENGINE_CLASSIC);
        
        // Step 3: Enter/move towards transition target `Classic`.
        CLASSIC_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for ManualQuickJump
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state MENU
////////////////////////////////////////////////////////////////////////////////

static void MENU_enter(ContextSm* sm)
{
    sm->state_id = ContextSm_StateId_MENU;
}

static void MENU_exit(ContextSm* sm)
{
    // Menu behavior
    // uml: exit / { ctx_menu_close(); }
    {
        // Step 1: execute action `ctx_menu_close();`
        ctx_menu_close();
    } // end of behavior for Menu
    
    sm->state_id = ContextSm_StateId_FIELD;
}

static void MENU_e0_turn(ContextSm* sm)
{
    // Menu behavior
    // uml: E0_TURN / { ctx_menu_scroll(); }
    {
        // Step 1: execute action `ctx_menu_scroll();`
        ctx_menu_scroll();
    } // end of behavior for Menu
    
    // No ancestor handles this event.
}

static void MENU_e1_click(ContextSm* sm)
{
    // Menu behavior
    // uml: E1_CLICK TransitionTo(Field.<ChoicePoint>(FieldResume))
    {
        // Step 1: Exit states until we reach `Field` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, ContextSm_StateId_FIELD);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `Field.<ChoicePoint>(FieldResume)`.
        // Field.<ChoicePoint>(FieldResume) is a pseudo state and cannot have an `enter` trigger.
        
        // Finish transition by calling pseudo state transition function.
        Field_ChoicePoint_FieldResume__transition(sm);
        return; // event processing immediately stops when a transition finishes. No other behaviors for this state are checked.
    } // end of behavior for Menu
    
    // No ancestor handles this event.
}

static void MENU_menu_timeout(ContextSm* sm)
{
    // Menu behavior
    // uml: MENU_TIMEOUT TransitionTo(Field.<ChoicePoint>(FieldResume))
    {
        // Step 1: Exit states until we reach `Field` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, ContextSm_StateId_FIELD);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `Field.<ChoicePoint>(FieldResume)`.
        // Field.<ChoicePoint>(FieldResume) is a pseudo state and cannot have an `enter` trigger.
        
        // Finish transition by calling pseudo state transition function.
        Field_ChoicePoint_FieldResume__transition(sm);
        return; // event processing immediately stops when a transition finishes. No other behaviors for this state are checked.
    } // end of behavior for Menu
    
    // No ancestor handles this event.
}

static void MENU_reconcile(ContextSm* sm)
{
    bool consume_event = false;
    
    // Menu behavior
    // uml: RECONCILE / { ctx_ptt_off(); } TransitionTo(Field.<ChoicePoint>(FieldResume))
    {
        // Step 1: Exit states until we reach `Field` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, ContextSm_StateId_FIELD);
        
        // Step 2: Transition action: `ctx_ptt_off();`.
        ctx_ptt_off();
        
        // Step 3: Enter/move towards transition target `Field.<ChoicePoint>(FieldResume)`.
        // Field.<ChoicePoint>(FieldResume) is a pseudo state and cannot have an `enter` trigger.
        
        // Finish transition by calling pseudo state transition function.
        Field_ChoicePoint_FieldResume__transition(sm);
        return; // event processing immediately stops when a transition finishes. No other behaviors for this state are checked.
    } // end of behavior for Menu
    
    // Check if event has been consumed before calling ancestor handler.
    if (!consume_event)
    {
        RUNNING_reconcile(sm);
    }
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state BANDMENU
////////////////////////////////////////////////////////////////////////////////

static void BANDMENU_enter(ContextSm* sm)
{
    sm->state_id = ContextSm_StateId_BANDMENU;
    
    // BandMenu behavior
    // uml: enter / { ctx_menu_open(CTX_MENU_BAND); }
    {
        // Step 1: execute action `ctx_menu_open(CTX_MENU_BAND);`
        ctx_menu_open(CTX_MENU_BAND);
    } // end of behavior for BandMenu
}

static void BANDMENU_exit(ContextSm* sm)
{
    sm->state_id = ContextSm_StateId_MENU;
}

static void BANDMENU_e0_click(ContextSm* sm)
{
    // BandMenu behavior
    // uml: E0_CLICK / { ctx_select_band(); } TransitionTo(Field.<ChoicePoint>(FieldResume))
    {
        // Step 1: Exit states until we reach `Field` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, ContextSm_StateId_FIELD);
        
        // Step 2: Transition action: `ctx_select_band();`.
        ctx_select_band();
        
        // Step 3: Enter/move towards transition target `Field.<ChoicePoint>(FieldResume)`.
        // Field.<ChoicePoint>(FieldResume) is a pseudo state and cannot have an `enter` trigger.
        
        // Finish transition by calling pseudo state transition function.
        Field_ChoicePoint_FieldResume__transition(sm);
        return; // event processing immediately stops when a transition finishes. No other behaviors for this state are checked.
    } // end of behavior for BandMenu
    
    // No ancestor handles this event.
}

static void BANDMENU_session_changed(ContextSm* sm)
{
    // BandMenu behavior
    // uml: SESSION_CHANGED [!ctx_band_change_allowed()] / { ctx_publish(CTX_PUB_MENU_WITHDRAWN, CTX_MENU_BAND); } TransitionTo(Field.<ChoicePoint>(FieldResume))
    if (!ctx_band_change_allowed())
    {
        // Step 1: Exit states until we reach `Field` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, ContextSm_StateId_FIELD);
        
        // Step 2: Transition action: `ctx_publish(CTX_PUB_MENU_WITHDRAWN, CTX_MENU_BAND);`.
        ctx_publish(CTX_PUB_MENU_WITHDRAWN, CTX_MENU_BAND);
        
        // Step 3: Enter/move towards transition target `Field.<ChoicePoint>(FieldResume)`.
        // Field.<ChoicePoint>(FieldResume) is a pseudo state and cannot have an `enter` trigger.
        
        // Finish transition by calling pseudo state transition function.
        Field_ChoicePoint_FieldResume__transition(sm);
        return; // event processing immediately stops when a transition finishes. No other behaviors for this state are checked.
    } // end of behavior for BandMenu
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state ENGINEMENU
////////////////////////////////////////////////////////////////////////////////

static void ENGINEMENU_enter(ContextSm* sm)
{
    sm->state_id = ContextSm_StateId_ENGINEMENU;
    
    // EngineMenu behavior
    // uml: enter / { ctx_menu_open(CTX_MENU_ENGINE); }
    {
        // Step 1: execute action `ctx_menu_open(CTX_MENU_ENGINE);`
        ctx_menu_open(CTX_MENU_ENGINE);
    } // end of behavior for EngineMenu
}

static void ENGINEMENU_exit(ContextSm* sm)
{
    sm->state_id = ContextSm_StateId_MENU;
}

static void ENGINEMENU_e0_click(ContextSm* sm)
{
    // EngineMenu behavior
    // uml: E0_CLICK TransitionTo(Field.<ChoicePoint>(EngineChoice))
    {
        // Step 1: Exit states until we reach `Field` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, ContextSm_StateId_FIELD);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `Field.<ChoicePoint>(EngineChoice)`.
        // Field.<ChoicePoint>(EngineChoice) is a pseudo state and cannot have an `enter` trigger.
        
        // Field.<ChoicePoint>(EngineChoice) behavior
        // uml: [ctx_highlight_is_current()] TransitionTo(Field.<ChoicePoint>(FieldResume))
        if (ctx_highlight_is_current())
        {
            // Step 1: Exit states until we reach `Field` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `Field.<ChoicePoint>(FieldResume)`.
            // Field.<ChoicePoint>(FieldResume) is a pseudo state and cannot have an `enter` trigger.
            
            // Finish transition by calling pseudo state transition function.
            Field_ChoicePoint_FieldResume__transition(sm);
            return; // event processing immediately stops when a transition finishes. No other behaviors for this state are checked.
        } // end of behavior for Field.<ChoicePoint>(EngineChoice)
        
        // Field.<ChoicePoint>(EngineChoice) behavior
        // uml: [ctx_highlight_is(CTX_ENGINE_CLASSIC)] / { ctx_select_engine(CTX_ENGINE_CLASSIC); } TransitionTo(Classic)
        if (ctx_highlight_is(CTX_ENGINE_CLASSIC))
        {
            // Step 1: Exit states until we reach `Field` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
            
            // Step 2: Transition action: `ctx_select_engine(CTX_ENGINE_CLASSIC);`.
            ctx_select_engine(CTX_ENGINE_CLASSIC);
            
            // Step 3: Enter/move towards transition target `Classic`.
            FIELDPAGE_enter(sm);
            CLASSIC_enter(sm);
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for Field.<ChoicePoint>(EngineChoice)
        
        // Field.<ChoicePoint>(EngineChoice) behavior
        // uml: / { ctx_select_engine(CTX_ENGINE_MANUAL); } TransitionTo(ManualDirect)
        {
            // Step 1: Exit states until we reach `Field` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
            
            // Step 2: Transition action: `ctx_select_engine(CTX_ENGINE_MANUAL);`.
            ctx_select_engine(CTX_ENGINE_MANUAL);
            
            // Step 3: Enter/move towards transition target `ManualDirect`.
            FIELDPAGE_enter(sm);
            MANUAL_enter(sm);
            MANUALDIRECT_enter(sm);
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for Field.<ChoicePoint>(EngineChoice)
    } // end of behavior for EngineMenu
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state INSTRUMENT
////////////////////////////////////////////////////////////////////////////////

static void INSTRUMENT_enter(ContextSm* sm)
{
    sm->state_id = ContextSm_StateId_INSTRUMENT;
    
    // Instrument behavior
    // uml: enter / { ctx_page_entered(CTX_PAGE_INSTRUMENT); }
    {
        // Step 1: execute action `ctx_page_entered(CTX_PAGE_INSTRUMENT);`
        ctx_page_entered(CTX_PAGE_INSTRUMENT);
    } // end of behavior for Instrument
}

static void INSTRUMENT_exit(ContextSm* sm)
{
    sm->state_id = ContextSm_StateId_RUNNING;
}

static void INSTRUMENT_shift_b0(ContextSm* sm)
{
    // Instrument behavior
    // uml: SHIFT_B0 [ctx_session_active()] / { ctx_reject(CTX_ACTION_MODE_SWITCH); }
    if (ctx_session_active())
    {
        // Step 1: execute action `ctx_reject(CTX_ACTION_MODE_SWITCH);`
        ctx_reject(CTX_ACTION_MODE_SWITCH);
    } // end of behavior for Instrument
    
    // Instrument behavior
    // uml: SHIFT_B0 [!ctx_session_active()] / { ctx_mode_changed(CTX_MODE_FIELD); } TransitionTo(Field.<ChoicePoint>(FieldResume))
    if (!ctx_session_active())
    {
        // Step 1: Exit states until we reach `Running` state (Least Common Ancestor for transition).
        INSTRUMENT_exit(sm);
        
        // Step 2: Transition action: `ctx_mode_changed(CTX_MODE_FIELD);`.
        ctx_mode_changed(CTX_MODE_FIELD);
        
        // Step 3: Enter/move towards transition target `Field.<ChoicePoint>(FieldResume)`.
        FIELD_enter(sm);
        // Field.<ChoicePoint>(FieldResume) is a pseudo state and cannot have an `enter` trigger.
        
        // Finish transition by calling pseudo state transition function.
        Field_ChoicePoint_FieldResume__transition(sm);
        return; // event processing immediately stops when a transition finishes. No other behaviors for this state are checked.
    } // end of behavior for Instrument
    
    // No ancestor handles this event.
}

static void INSTRUMENT_shift_e0(ContextSm* sm)
{
    // Instrument behavior
    // uml: SHIFT_E0 TransitionTo(Utility)
    {
        // Step 1: Exit states until we reach `Running` state (Least Common Ancestor for transition).
        INSTRUMENT_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `Utility`.
        UTILITY_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for Instrument
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state UTILITY
////////////////////////////////////////////////////////////////////////////////

static void UTILITY_enter(ContextSm* sm)
{
    sm->state_id = ContextSm_StateId_UTILITY;
    
    // Utility behavior
    // uml: enter / { ctx_utility_opened(); }
    {
        // Step 1: execute action `ctx_utility_opened();`
        ctx_utility_opened();
    } // end of behavior for Utility
}

static void UTILITY_exit(ContextSm* sm)
{
    // Utility behavior
    // uml: exit / { ctx_utility_closed(); }
    {
        // Step 1: execute action `ctx_utility_closed();`
        ctx_utility_closed();
    } // end of behavior for Utility
    
    sm->state_id = ContextSm_StateId_RUNNING;
}

static void UTILITY_e0_click(ContextSm* sm)
{
    // Utility behavior
    // uml: E0_CLICK / { ctx_command(CTX_CMD_UTILITY_SELECT, 0); }
    {
        // Step 1: execute action `ctx_command(CTX_CMD_UTILITY_SELECT, 0);`
        ctx_command(CTX_CMD_UTILITY_SELECT, 0);
    } // end of behavior for Utility
    
    // No ancestor handles this event.
}

static void UTILITY_e0_turn(ContextSm* sm)
{
    // Utility behavior
    // uml: E0_TURN / { ctx_command(CTX_CMD_UTILITY_SCROLL, ctx_detents()); }
    {
        // Step 1: execute action `ctx_command(CTX_CMD_UTILITY_SCROLL, ctx_detents());`
        ctx_command(CTX_CMD_UTILITY_SCROLL, ctx_detents());
    } // end of behavior for Utility
    
    // No ancestor handles this event.
}

static void UTILITY_e1_click(ContextSm* sm)
{
    // Utility behavior
    // uml: E1_CLICK [!ctx_utility_at_root()] / { ctx_command(CTX_CMD_UTILITY_BACK, 0); }
    if (!ctx_utility_at_root())
    {
        // Step 1: execute action `ctx_command(CTX_CMD_UTILITY_BACK, 0);`
        ctx_command(CTX_CMD_UTILITY_BACK, 0);
    } // end of behavior for Utility
    
    // Utility behavior
    // uml: E1_CLICK [ctx_utility_at_root()] TransitionTo(Running.<ChoicePoint>(UtilityResume))
    if (ctx_utility_at_root())
    {
        // Step 1: Exit states until we reach `Running` state (Least Common Ancestor for transition).
        UTILITY_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `Running.<ChoicePoint>(UtilityResume)`.
        // Running.<ChoicePoint>(UtilityResume) is a pseudo state and cannot have an `enter` trigger.
        
        // Finish transition by calling pseudo state transition function.
        Running_ChoicePoint_UtilityResume__transition(sm);
        return; // event processing immediately stops when a transition finishes. No other behaviors for this state are checked.
    } // end of behavior for Utility
    
    // No ancestor handles this event.
}

static void UTILITY_e3_hold(ContextSm* sm)
{
    // Utility behavior
    // uml: E3_HOLD TransitionTo(Running.<ChoicePoint>(UtilityResume))
    {
        // Step 1: Exit states until we reach `Running` state (Least Common Ancestor for transition).
        UTILITY_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `Running.<ChoicePoint>(UtilityResume)`.
        // Running.<ChoicePoint>(UtilityResume) is a pseudo state and cannot have an `enter` trigger.
        
        // Finish transition by calling pseudo state transition function.
        Running_ChoicePoint_UtilityResume__transition(sm);
        return; // event processing immediately stops when a transition finishes. No other behaviors for this state are checked.
    } // end of behavior for Utility
    
    // No ancestor handles this event.
}

// Thread safe. This function can be disabled with `outputStateIdToStringFunction` setting.
char const * ContextSm_state_id_to_string(ContextSm_StateId id)
{
    switch (id)
    {
        case ContextSm_StateId_ROOT: return "ROOT";
        case ContextSm_StateId_RUNNING: return "RUNNING";
        case ContextSm_StateId_FIELD: return "FIELD";
        case ContextSm_StateId_FIELDPAGE: return "FIELDPAGE";
        case ContextSm_StateId_CLASSIC: return "CLASSIC";
        case ContextSm_StateId_MANUAL: return "MANUAL";
        case ContextSm_StateId_MANUALDIRECT: return "MANUALDIRECT";
        case ContextSm_StateId_MANUALQUICKJUMP: return "MANUALQUICKJUMP";
        case ContextSm_StateId_MENU: return "MENU";
        case ContextSm_StateId_BANDMENU: return "BANDMENU";
        case ContextSm_StateId_ENGINEMENU: return "ENGINEMENU";
        case ContextSm_StateId_INSTRUMENT: return "INSTRUMENT";
        case ContextSm_StateId_UTILITY: return "UTILITY";
        default: return "?";
    }
}

// Thread safe. This function can be disabled with `outputEventIdToStringFunction` setting.
char const * ContextSm_event_id_to_string(ContextSm_EventId id)
{
    switch (id)
    {
        case ContextSm_EventId_E0_CLICK: return "E0_CLICK";
        case ContextSm_EventId_E0_TURN: return "E0_TURN";
        case ContextSm_EventId_E1_CLICK: return "E1_CLICK";
        case ContextSm_EventId_E1_HOLD: return "E1_HOLD";
        case ContextSm_EventId_E1_TURN: return "E1_TURN";
        case ContextSm_EventId_E2_HOLD: return "E2_HOLD";
        case ContextSm_EventId_E3_CLICK: return "E3_CLICK";
        case ContextSm_EventId_E3_HOLD: return "E3_HOLD";
        case ContextSm_EventId_MENU_TIMEOUT: return "MENU_TIMEOUT";
        case ContextSm_EventId_PTT_OFF: return "PTT_OFF";
        case ContextSm_EventId_PTT_ON: return "PTT_ON";
        case ContextSm_EventId_RECONCILE: return "RECONCILE";
        case ContextSm_EventId_SESSION_CHANGED: return "SESSION_CHANGED";
        case ContextSm_EventId_SHIFT_B0: return "SHIFT_B0";
        case ContextSm_EventId_SHIFT_B1: return "SHIFT_B1";
        case ContextSm_EventId_SHIFT_CHORD: return "SHIFT_CHORD";
        case ContextSm_EventId_SHIFT_E0: return "SHIFT_E0";
        case ContextSm_EventId_SHIFT_E1: return "SHIFT_E1";
        default: return "?";
    }
}

// Returns the parent state for a given state. Returns ROOT if input has no parent.
// Thread safe. This function can be disabled with `outputGetParentIdFunction` setting.
ContextSm_StateId ContextSm_get_parent_id(ContextSm_StateId id)
{
    switch (id)
    {
        case ContextSm_StateId_ROOT: return ContextSm_StateId_ROOT;
        case ContextSm_StateId_RUNNING: return ContextSm_StateId_ROOT;
        case ContextSm_StateId_FIELD: return ContextSm_StateId_RUNNING;
        case ContextSm_StateId_FIELDPAGE: return ContextSm_StateId_FIELD;
        case ContextSm_StateId_CLASSIC: return ContextSm_StateId_FIELDPAGE;
        case ContextSm_StateId_MANUAL: return ContextSm_StateId_FIELDPAGE;
        case ContextSm_StateId_MANUALDIRECT: return ContextSm_StateId_MANUAL;
        case ContextSm_StateId_MANUALQUICKJUMP: return ContextSm_StateId_MANUAL;
        case ContextSm_StateId_MENU: return ContextSm_StateId_FIELD;
        case ContextSm_StateId_BANDMENU: return ContextSm_StateId_MENU;
        case ContextSm_StateId_ENGINEMENU: return ContextSm_StateId_MENU;
        case ContextSm_StateId_INSTRUMENT: return ContextSm_StateId_RUNNING;
        case ContextSm_StateId_UTILITY: return ContextSm_StateId_RUNNING;
        default: return ContextSm_StateId_ROOT;
    }
}
