// Autogenerated with StateSmith 0.22.2+0c32be37bf4d4fee5499780a5ef37a7996c192f9.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

#ifndef SPOOKY_CONTEXT_SM_H
#define SPOOKY_CONTEXT_SM_H
#include <stdint.h>

typedef enum ContextSm_EventId
{
    ContextSm_EventId_E0_CLICK = 0,
    ContextSm_EventId_E0_TURN = 1,
    ContextSm_EventId_E1_CLICK = 2,
    ContextSm_EventId_E1_HOLD = 3,
    ContextSm_EventId_E1_TURN = 4,
    ContextSm_EventId_E2_HOLD = 5,
    ContextSm_EventId_E3_CLICK = 6,
    ContextSm_EventId_E3_HOLD = 7,
    ContextSm_EventId_MENU_TIMEOUT = 8,
    ContextSm_EventId_PTT_OFF = 9,
    ContextSm_EventId_PTT_ON = 10,
    ContextSm_EventId_RECONCILE = 11,
    ContextSm_EventId_SESSION_CHANGED = 12,
    ContextSm_EventId_SHIFT_B0 = 13,
    ContextSm_EventId_SHIFT_B1 = 14,
    ContextSm_EventId_SHIFT_CHORD = 15,
    ContextSm_EventId_SHIFT_E0 = 16,
    ContextSm_EventId_SHIFT_E1 = 17
} ContextSm_EventId;

#define ContextSm_EventIdCount (18)

typedef enum ContextSm_StateId
{
    ContextSm_StateId_ROOT = 0,
    ContextSm_StateId_RUNNING = 1,
    ContextSm_StateId_FIELD = 2,
    ContextSm_StateId_FIELDPAGE = 3,
    ContextSm_StateId_CLASSIC = 4,
    ContextSm_StateId_MANUAL = 5,
    ContextSm_StateId_MANUALDIRECT = 6,
    ContextSm_StateId_MANUALQUICKJUMP = 7,
    ContextSm_StateId_MENU = 8,
    ContextSm_StateId_BANDMENU = 9,
    ContextSm_StateId_ENGINEMENU = 10,
    ContextSm_StateId_INSTRUMENT = 11,
    ContextSm_StateId_UTILITY = 12
} ContextSm_StateId;

#define ContextSm_StateIdCount (13)

// Subtree meta data generation can be disabled in settings.
// Details: https://github.com/StateSmith/StateSmith/issues/538
#define ContextSm_ROOT_SubtreeEndId (12)  // State 'ContextSm' subtree extends from itself (id: 0) to state 'Utility' (id: 12)
#define ContextSm_RUNNING_SubtreeEndId (12)  // State 'Running' subtree extends from itself (id: 1) to state 'Utility' (id: 12)
#define ContextSm_FIELD_SubtreeEndId (10)  // State 'Field' subtree extends from itself (id: 2) to state 'EngineMenu' (id: 10)
#define ContextSm_FIELDPAGE_SubtreeEndId (7)  // State 'FieldPage' subtree extends from itself (id: 3) to state 'ManualQuickJump' (id: 7)
#define ContextSm_CLASSIC_SubtreeEndId (4)  // State 'Classic' subtree extends from itself (id: 4) to state 'Classic' (id: 4)
#define ContextSm_MANUAL_SubtreeEndId (7)  // State 'Manual' subtree extends from itself (id: 5) to state 'ManualQuickJump' (id: 7)
#define ContextSm_MANUALDIRECT_SubtreeEndId (6)  // State 'ManualDirect' subtree extends from itself (id: 6) to state 'ManualDirect' (id: 6)
#define ContextSm_MANUALQUICKJUMP_SubtreeEndId (7)  // State 'ManualQuickJump' subtree extends from itself (id: 7) to state 'ManualQuickJump' (id: 7)
#define ContextSm_MENU_SubtreeEndId (10)  // State 'Menu' subtree extends from itself (id: 8) to state 'EngineMenu' (id: 10)
#define ContextSm_BANDMENU_SubtreeEndId (9)  // State 'BandMenu' subtree extends from itself (id: 9) to state 'BandMenu' (id: 9)
#define ContextSm_ENGINEMENU_SubtreeEndId (10)  // State 'EngineMenu' subtree extends from itself (id: 10) to state 'EngineMenu' (id: 10)
#define ContextSm_INSTRUMENT_SubtreeEndId (11)  // State 'Instrument' subtree extends from itself (id: 11) to state 'Instrument' (id: 11)
#define ContextSm_UTILITY_SubtreeEndId (12)  // State 'Utility' subtree extends from itself (id: 12) to state 'Utility' (id: 12)


// Generated state machine
// forward declaration
typedef struct ContextSm ContextSm;

// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void ContextSm_ctor(ContextSm* sm);

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void ContextSm_start(ContextSm* sm);

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void ContextSm_dispatch_event(ContextSm* sm, ContextSm_EventId event_id);

// Thread safe. This function can be disabled with `outputStateIdToStringFunction` setting.
char const * ContextSm_state_id_to_string(ContextSm_StateId id);

// Thread safe. This function can be disabled with `outputEventIdToStringFunction` setting.
char const * ContextSm_event_id_to_string(ContextSm_EventId id);

// Returns the parent state for a given state. Returns ROOT if input has no parent.
// Thread safe. This function can be disabled with `outputGetParentIdFunction` setting.
ContextSm_StateId ContextSm_get_parent_id(ContextSm_StateId id);

// Generated state machine
struct ContextSm
{
    // Used internally by state machine. Feel free to inspect, but don't modify.
    ContextSm_StateId state_id;
};

#endif // SPOOKY_CONTEXT_SM_H
