// Autogenerated with StateSmith 0.22.2+0c32be37bf4d4fee5499780a5ef37a7996c192f9.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

#ifndef SPOOKY_INPUT_RESOLUTION_SM_H
#define SPOOKY_INPUT_RESOLUTION_SM_H
#include <stdint.h>

typedef enum InputResolutionSm_EventId
{
    InputResolutionSm_EventId_BTN0_PRESS = 0,
    InputResolutionSm_EventId_BTN0_RELEASE = 1,
    InputResolutionSm_EventId_ENC0_PRESS = 2,
    InputResolutionSm_EventId_HOLD_THRESHOLD = 3,
    InputResolutionSm_EventId_INPUT = 4,
    InputResolutionSm_EventId_RECONCILE = 5,
    InputResolutionSm_EventId_SESSION_CHANGED = 6
} InputResolutionSm_EventId;

#define InputResolutionSm_EventIdCount (7)

typedef enum InputResolutionSm_StateId
{
    InputResolutionSm_StateId_ROOT = 0,
    InputResolutionSm_StateId_BTN0HELD = 1,
    InputResolutionSm_StateId_CONSUMED = 2,
    InputResolutionSm_StateId_PENDING = 3,
    InputResolutionSm_StateId_PROMPT = 4,
    InputResolutionSm_StateId_STARTPROMPT = 5,
    InputResolutionSm_StateId_STOPPROMPT = 6,
    InputResolutionSm_StateId_NEUTRAL = 7
} InputResolutionSm_StateId;

#define InputResolutionSm_StateIdCount (8)

// Subtree meta data generation can be disabled in settings.
// Details: https://github.com/StateSmith/StateSmith/issues/538
#define InputResolutionSm_ROOT_SubtreeEndId (7)  // State 'InputResolutionSm' subtree extends from itself (id: 0) to state 'Neutral' (id: 7)
#define InputResolutionSm_BTN0HELD_SubtreeEndId (6)  // State 'Btn0Held' subtree extends from itself (id: 1) to state 'StopPrompt' (id: 6)
#define InputResolutionSm_CONSUMED_SubtreeEndId (2)  // State 'Consumed' subtree extends from itself (id: 2) to state 'Consumed' (id: 2)
#define InputResolutionSm_PENDING_SubtreeEndId (3)  // State 'Pending' subtree extends from itself (id: 3) to state 'Pending' (id: 3)
#define InputResolutionSm_PROMPT_SubtreeEndId (6)  // State 'Prompt' subtree extends from itself (id: 4) to state 'StopPrompt' (id: 6)
#define InputResolutionSm_STARTPROMPT_SubtreeEndId (5)  // State 'StartPrompt' subtree extends from itself (id: 5) to state 'StartPrompt' (id: 5)
#define InputResolutionSm_STOPPROMPT_SubtreeEndId (6)  // State 'StopPrompt' subtree extends from itself (id: 6) to state 'StopPrompt' (id: 6)
#define InputResolutionSm_NEUTRAL_SubtreeEndId (7)  // State 'Neutral' subtree extends from itself (id: 7) to state 'Neutral' (id: 7)


// Generated state machine
// forward declaration
typedef struct InputResolutionSm InputResolutionSm;

// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void InputResolutionSm_ctor(InputResolutionSm* sm);

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void InputResolutionSm_start(InputResolutionSm* sm);

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void InputResolutionSm_dispatch_event(InputResolutionSm* sm, InputResolutionSm_EventId event_id);

// Thread safe. This function can be disabled with `outputStateIdToStringFunction` setting.
char const * InputResolutionSm_state_id_to_string(InputResolutionSm_StateId id);

// Thread safe. This function can be disabled with `outputEventIdToStringFunction` setting.
char const * InputResolutionSm_event_id_to_string(InputResolutionSm_EventId id);

// Returns the parent state for a given state. Returns ROOT if input has no parent.
// Thread safe. This function can be disabled with `outputGetParentIdFunction` setting.
InputResolutionSm_StateId InputResolutionSm_get_parent_id(InputResolutionSm_StateId id);

// Generated state machine
struct InputResolutionSm
{
    // Used internally by state machine. Feel free to inspect, but don't modify.
    InputResolutionSm_StateId state_id;
};

#endif // SPOOKY_INPUT_RESOLUTION_SM_H
