// Autogenerated with StateSmith 0.22.2+0c32be37bf4d4fee5499780a5ef37a7996c192f9.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

#include "InputResolutionSm.h"
#include <stdbool.h> // required for `consume_event` flag
#include <string.h> // for memset
#include "input_resolution_port.h"


// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(InputResolutionSm* sm, InputResolutionSm_StateId desired_state);

static void ROOT_enter(InputResolutionSm* sm);

static void BTN0HELD_enter(InputResolutionSm* sm);

static void BTN0HELD_exit(InputResolutionSm* sm);

static void BTN0HELD_btn0_press(InputResolutionSm* sm);

static void BTN0HELD_btn0_release(InputResolutionSm* sm);

static void BTN0HELD_enc0_press(InputResolutionSm* sm);

static void BTN0HELD_input(InputResolutionSm* sm);

static void BTN0HELD_reconcile(InputResolutionSm* sm);

static void CONSUMED_enter(InputResolutionSm* sm);

static void CONSUMED_exit(InputResolutionSm* sm);

static void PENDING_enter(InputResolutionSm* sm);

static void PENDING_exit(InputResolutionSm* sm);

static void PENDING_hold_threshold(InputResolutionSm* sm);

static void PROMPT_enter(InputResolutionSm* sm);

static void PROMPT_exit(InputResolutionSm* sm);

static void PROMPT_btn0_release(InputResolutionSm* sm);

static void PROMPT_reconcile(InputResolutionSm* sm);

static void PROMPT_session_changed(InputResolutionSm* sm);

static void STARTPROMPT_enter(InputResolutionSm* sm);

static void STARTPROMPT_exit(InputResolutionSm* sm);

static void STARTPROMPT_enc0_press(InputResolutionSm* sm);

static void STOPPROMPT_enter(InputResolutionSm* sm);

static void STOPPROMPT_exit(InputResolutionSm* sm);

static void STOPPROMPT_enc0_press(InputResolutionSm* sm);

static void NEUTRAL_enter(InputResolutionSm* sm);

static void NEUTRAL_exit(InputResolutionSm* sm);

static void NEUTRAL_btn0_press(InputResolutionSm* sm);

static void NEUTRAL_btn0_release(InputResolutionSm* sm);

static void NEUTRAL_enc0_press(InputResolutionSm* sm);

static void NEUTRAL_input(InputResolutionSm* sm);

static void NEUTRAL_reconcile(InputResolutionSm* sm);


// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void InputResolutionSm_ctor(InputResolutionSm* sm)
{
    memset(sm, 0, sizeof(*sm));
}

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void InputResolutionSm_start(InputResolutionSm* sm)
{
    ROOT_enter(sm);
    // ROOT behavior
    // uml: TransitionTo(ROOT.<InitialState>)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `ROOT.<InitialState>`.
        // ROOT.<InitialState> is a pseudo state and cannot have an `enter` trigger.
        
        // ROOT.<InitialState> behavior
        // uml: TransitionTo(Neutral)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `Neutral`.
            NEUTRAL_enter(sm);
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for ROOT.<InitialState>
    } // end of behavior for ROOT
}

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void InputResolutionSm_dispatch_event(InputResolutionSm* sm, InputResolutionSm_EventId event_id)
{
    switch (sm->state_id)
    {
        // STATE: InputResolutionSm
        case InputResolutionSm_StateId_ROOT:
            // No events handled by this state (or its ancestors).
            break;
        
        // STATE: Btn0Held
        case InputResolutionSm_StateId_BTN0HELD:
            switch (event_id)
            {
                case InputResolutionSm_EventId_BTN0_PRESS: BTN0HELD_btn0_press(sm); break;
                case InputResolutionSm_EventId_ENC0_PRESS: BTN0HELD_enc0_press(sm); break;
                case InputResolutionSm_EventId_INPUT: BTN0HELD_input(sm); break;
                case InputResolutionSm_EventId_BTN0_RELEASE: BTN0HELD_btn0_release(sm); break;
                case InputResolutionSm_EventId_RECONCILE: BTN0HELD_reconcile(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: Consumed
        case InputResolutionSm_StateId_CONSUMED:
            switch (event_id)
            {
                case InputResolutionSm_EventId_BTN0_PRESS: BTN0HELD_btn0_press(sm); break; // First ancestor handler for this event
                case InputResolutionSm_EventId_BTN0_RELEASE: BTN0HELD_btn0_release(sm); break; // First ancestor handler for this event
                case InputResolutionSm_EventId_ENC0_PRESS: BTN0HELD_enc0_press(sm); break; // First ancestor handler for this event
                case InputResolutionSm_EventId_INPUT: BTN0HELD_input(sm); break; // First ancestor handler for this event
                case InputResolutionSm_EventId_RECONCILE: BTN0HELD_reconcile(sm); break; // First ancestor handler for this event
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: Pending
        case InputResolutionSm_StateId_PENDING:
            switch (event_id)
            {
                case InputResolutionSm_EventId_HOLD_THRESHOLD: PENDING_hold_threshold(sm); break;
                case InputResolutionSm_EventId_BTN0_PRESS: BTN0HELD_btn0_press(sm); break; // First ancestor handler for this event
                case InputResolutionSm_EventId_BTN0_RELEASE: BTN0HELD_btn0_release(sm); break; // First ancestor handler for this event
                case InputResolutionSm_EventId_ENC0_PRESS: BTN0HELD_enc0_press(sm); break; // First ancestor handler for this event
                case InputResolutionSm_EventId_INPUT: BTN0HELD_input(sm); break; // First ancestor handler for this event
                case InputResolutionSm_EventId_RECONCILE: BTN0HELD_reconcile(sm); break; // First ancestor handler for this event
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: Prompt
        case InputResolutionSm_StateId_PROMPT:
            switch (event_id)
            {
                case InputResolutionSm_EventId_BTN0_RELEASE: PROMPT_btn0_release(sm); break;
                case InputResolutionSm_EventId_RECONCILE: PROMPT_reconcile(sm); break;
                case InputResolutionSm_EventId_SESSION_CHANGED: PROMPT_session_changed(sm); break;
                case InputResolutionSm_EventId_BTN0_PRESS: BTN0HELD_btn0_press(sm); break; // First ancestor handler for this event
                case InputResolutionSm_EventId_ENC0_PRESS: BTN0HELD_enc0_press(sm); break; // First ancestor handler for this event
                case InputResolutionSm_EventId_INPUT: BTN0HELD_input(sm); break; // First ancestor handler for this event
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: StartPrompt
        case InputResolutionSm_StateId_STARTPROMPT:
            switch (event_id)
            {
                case InputResolutionSm_EventId_ENC0_PRESS: STARTPROMPT_enc0_press(sm); break;
                case InputResolutionSm_EventId_BTN0_PRESS: BTN0HELD_btn0_press(sm); break; // First ancestor handler for this event
                case InputResolutionSm_EventId_BTN0_RELEASE: PROMPT_btn0_release(sm); break; // First ancestor handler for this event
                case InputResolutionSm_EventId_INPUT: BTN0HELD_input(sm); break; // First ancestor handler for this event
                case InputResolutionSm_EventId_RECONCILE: PROMPT_reconcile(sm); break; // First ancestor handler for this event
                case InputResolutionSm_EventId_SESSION_CHANGED: PROMPT_session_changed(sm); break; // First ancestor handler for this event
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: StopPrompt
        case InputResolutionSm_StateId_STOPPROMPT:
            switch (event_id)
            {
                case InputResolutionSm_EventId_ENC0_PRESS: STOPPROMPT_enc0_press(sm); break;
                case InputResolutionSm_EventId_BTN0_PRESS: BTN0HELD_btn0_press(sm); break; // First ancestor handler for this event
                case InputResolutionSm_EventId_BTN0_RELEASE: PROMPT_btn0_release(sm); break; // First ancestor handler for this event
                case InputResolutionSm_EventId_INPUT: BTN0HELD_input(sm); break; // First ancestor handler for this event
                case InputResolutionSm_EventId_RECONCILE: PROMPT_reconcile(sm); break; // First ancestor handler for this event
                case InputResolutionSm_EventId_SESSION_CHANGED: PROMPT_session_changed(sm); break; // First ancestor handler for this event
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: Neutral
        case InputResolutionSm_StateId_NEUTRAL:
            switch (event_id)
            {
                case InputResolutionSm_EventId_BTN0_PRESS: NEUTRAL_btn0_press(sm); break;
                case InputResolutionSm_EventId_BTN0_RELEASE: NEUTRAL_btn0_release(sm); break;
                case InputResolutionSm_EventId_ENC0_PRESS: NEUTRAL_enc0_press(sm); break;
                case InputResolutionSm_EventId_INPUT: NEUTRAL_input(sm); break;
                case InputResolutionSm_EventId_RECONCILE: NEUTRAL_reconcile(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
    }
    
}

// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(InputResolutionSm* sm, InputResolutionSm_StateId desired_state)
{
    while (sm->state_id != desired_state)
    {
        switch (sm->state_id)
        {
            case InputResolutionSm_StateId_BTN0HELD: BTN0HELD_exit(sm); break;
            
            case InputResolutionSm_StateId_CONSUMED: CONSUMED_exit(sm); break;
            
            case InputResolutionSm_StateId_PENDING: PENDING_exit(sm); break;
            
            case InputResolutionSm_StateId_PROMPT: PROMPT_exit(sm); break;
            
            case InputResolutionSm_StateId_STARTPROMPT: STARTPROMPT_exit(sm); break;
            
            case InputResolutionSm_StateId_STOPPROMPT: STOPPROMPT_exit(sm); break;
            
            case InputResolutionSm_StateId_NEUTRAL: NEUTRAL_exit(sm); break;
            
            default: return;  // Just to be safe. Prevents infinite loop if state ID memory is somehow corrupted.
        }
    }
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state ROOT
////////////////////////////////////////////////////////////////////////////////

static void ROOT_enter(InputResolutionSm* sm)
{
    sm->state_id = InputResolutionSm_StateId_ROOT;
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state BTN0HELD
////////////////////////////////////////////////////////////////////////////////

static void BTN0HELD_enter(InputResolutionSm* sm)
{
    sm->state_id = InputResolutionSm_StateId_BTN0HELD;
}

static void BTN0HELD_exit(InputResolutionSm* sm)
{
    sm->state_id = InputResolutionSm_StateId_ROOT;
}

static void BTN0HELD_btn0_press(InputResolutionSm* sm)
{
    // Btn0Held behavior
    // uml: BTN0_PRESS / { inp_swallow(); }
    {
        // Step 1: execute action `inp_swallow();`
        inp_swallow();
    } // end of behavior for Btn0Held
    
    // No ancestor handles this event.
}

static void BTN0HELD_btn0_release(InputResolutionSm* sm)
{
    // Btn0Held behavior
    // uml: BTN0_RELEASE / { inp_swallow(); } TransitionTo(Neutral)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, InputResolutionSm_StateId_ROOT);
        
        // Step 2: Transition action: `inp_swallow();`.
        inp_swallow();
        
        // Step 3: Enter/move towards transition target `Neutral`.
        NEUTRAL_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for Btn0Held
    
    // No ancestor handles this event.
}

static void BTN0HELD_enc0_press(InputResolutionSm* sm)
{
    // Btn0Held behavior
    // uml: ENC0_PRESS / { inp_swallow(); }
    {
        // Step 1: execute action `inp_swallow();`
        inp_swallow();
    } // end of behavior for Btn0Held
    
    // No ancestor handles this event.
}

static void BTN0HELD_input(InputResolutionSm* sm)
{
    // Btn0Held behavior
    // uml: INPUT [inp_input_is_delivered_release()] / { inp_deliver(); }
    if (inp_input_is_delivered_release())
    {
        // Step 1: execute action `inp_deliver();`
        inp_deliver();
    } // end of behavior for Btn0Held
    
    // Btn0Held behavior
    // uml: INPUT [!inp_input_is_delivered_release()] / { inp_swallow(); }
    if (!inp_input_is_delivered_release())
    {
        // Step 1: execute action `inp_swallow();`
        inp_swallow();
    } // end of behavior for Btn0Held
    
    // No ancestor handles this event.
}

static void BTN0HELD_reconcile(InputResolutionSm* sm)
{
    // Btn0Held behavior
    // uml: RECONCILE / { inp_release_all(); } TransitionTo(Neutral)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, InputResolutionSm_StateId_ROOT);
        
        // Step 2: Transition action: `inp_release_all();`.
        inp_release_all();
        
        // Step 3: Enter/move towards transition target `Neutral`.
        NEUTRAL_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for Btn0Held
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state CONSUMED
////////////////////////////////////////////////////////////////////////////////

static void CONSUMED_enter(InputResolutionSm* sm)
{
    sm->state_id = InputResolutionSm_StateId_CONSUMED;
}

static void CONSUMED_exit(InputResolutionSm* sm)
{
    sm->state_id = InputResolutionSm_StateId_BTN0HELD;
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state PENDING
////////////////////////////////////////////////////////////////////////////////

static void PENDING_enter(InputResolutionSm* sm)
{
    sm->state_id = InputResolutionSm_StateId_PENDING;
    
    // Pending behavior
    // uml: enter / { inp_start_hold_timer(); }
    {
        // Step 1: execute action `inp_start_hold_timer();`
        inp_start_hold_timer();
    } // end of behavior for Pending
}

static void PENDING_exit(InputResolutionSm* sm)
{
    // Pending behavior
    // uml: exit / { inp_cancel_hold_timer(); }
    {
        // Step 1: execute action `inp_cancel_hold_timer();`
        inp_cancel_hold_timer();
    } // end of behavior for Pending
    
    sm->state_id = InputResolutionSm_StateId_BTN0HELD;
}

static void PENDING_hold_threshold(InputResolutionSm* sm)
{
    // Pending behavior
    // uml: HOLD_THRESHOLD [!inp_session_active()] TransitionTo(StartPrompt)
    if (!inp_session_active())
    {
        // Step 1: Exit states until we reach `Btn0Held` state (Least Common Ancestor for transition).
        PENDING_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `StartPrompt`.
        PROMPT_enter(sm);
        STARTPROMPT_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for Pending
    
    // Pending behavior
    // uml: HOLD_THRESHOLD [inp_session_active()] TransitionTo(StopPrompt)
    if (inp_session_active())
    {
        // Step 1: Exit states until we reach `Btn0Held` state (Least Common Ancestor for transition).
        PENDING_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `StopPrompt`.
        PROMPT_enter(sm);
        STOPPROMPT_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for Pending
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state PROMPT
////////////////////////////////////////////////////////////////////////////////

static void PROMPT_enter(InputResolutionSm* sm)
{
    sm->state_id = InputResolutionSm_StateId_PROMPT;
}

static void PROMPT_exit(InputResolutionSm* sm)
{
    sm->state_id = InputResolutionSm_StateId_BTN0HELD;
}

static void PROMPT_btn0_release(InputResolutionSm* sm)
{
    bool consume_event = false;
    
    // Prompt behavior
    // uml: BTN0_RELEASE / { inp_swallow(); inp_publish(INP_PUB_PROMPT_CANCELLED); } TransitionTo(Neutral)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, InputResolutionSm_StateId_ROOT);
        
        // Step 2: Transition action: `inp_swallow(); inp_publish(INP_PUB_PROMPT_CANCELLED);`.
        inp_swallow(); inp_publish(INP_PUB_PROMPT_CANCELLED);
        
        // Step 3: Enter/move towards transition target `Neutral`.
        NEUTRAL_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for Prompt
    
    // Check if event has been consumed before calling ancestor handler.
    if (!consume_event)
    {
        BTN0HELD_btn0_release(sm);
    }
}

static void PROMPT_reconcile(InputResolutionSm* sm)
{
    bool consume_event = false;
    
    // Prompt behavior
    // uml: RECONCILE / { inp_publish(INP_PUB_PROMPT_CANCELLED); inp_release_all(); } TransitionTo(Neutral)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, InputResolutionSm_StateId_ROOT);
        
        // Step 2: Transition action: `inp_publish(INP_PUB_PROMPT_CANCELLED); inp_release_all();`.
        inp_publish(INP_PUB_PROMPT_CANCELLED); inp_release_all();
        
        // Step 3: Enter/move towards transition target `Neutral`.
        NEUTRAL_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for Prompt
    
    // Check if event has been consumed before calling ancestor handler.
    if (!consume_event)
    {
        BTN0HELD_reconcile(sm);
    }
}

static void PROMPT_session_changed(InputResolutionSm* sm)
{
    // Prompt behavior
    // uml: SESSION_CHANGED / { inp_publish(INP_PUB_PROMPT_WITHDRAWN); } TransitionTo(Consumed)
    {
        // Step 1: Exit states until we reach `Btn0Held` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, InputResolutionSm_StateId_BTN0HELD);
        
        // Step 2: Transition action: `inp_publish(INP_PUB_PROMPT_WITHDRAWN);`.
        inp_publish(INP_PUB_PROMPT_WITHDRAWN);
        
        // Step 3: Enter/move towards transition target `Consumed`.
        CONSUMED_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for Prompt
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state STARTPROMPT
////////////////////////////////////////////////////////////////////////////////

static void STARTPROMPT_enter(InputResolutionSm* sm)
{
    sm->state_id = InputResolutionSm_StateId_STARTPROMPT;
    
    // StartPrompt behavior
    // uml: enter / { inp_publish(INP_PUB_PROMPT_OPENED_START); }
    {
        // Step 1: execute action `inp_publish(INP_PUB_PROMPT_OPENED_START);`
        inp_publish(INP_PUB_PROMPT_OPENED_START);
    } // end of behavior for StartPrompt
}

static void STARTPROMPT_exit(InputResolutionSm* sm)
{
    sm->state_id = InputResolutionSm_StateId_PROMPT;
}

static void STARTPROMPT_enc0_press(InputResolutionSm* sm)
{
    bool consume_event = false;
    
    // StartPrompt behavior
    // uml: ENC0_PRESS / { inp_swallow(); inp_publish(INP_PUB_PROMPT_CONFIRMED_START); inp_issue(INP_CMD_START_SESSION); } TransitionTo(Consumed)
    {
        // Step 1: Exit states until we reach `Btn0Held` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, InputResolutionSm_StateId_BTN0HELD);
        
        // Step 2: Transition action: `inp_swallow(); inp_publish(INP_PUB_PROMPT_CONFIRMED_START); inp_issue(INP_CMD_START_SESSION);`.
        inp_swallow(); inp_publish(INP_PUB_PROMPT_CONFIRMED_START); inp_issue(INP_CMD_START_SESSION);
        
        // Step 3: Enter/move towards transition target `Consumed`.
        CONSUMED_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for StartPrompt
    
    // Check if event has been consumed before calling ancestor handler.
    if (!consume_event)
    {
        BTN0HELD_enc0_press(sm);
    }
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state STOPPROMPT
////////////////////////////////////////////////////////////////////////////////

static void STOPPROMPT_enter(InputResolutionSm* sm)
{
    sm->state_id = InputResolutionSm_StateId_STOPPROMPT;
    
    // StopPrompt behavior
    // uml: enter / { inp_publish(INP_PUB_PROMPT_OPENED_STOP); }
    {
        // Step 1: execute action `inp_publish(INP_PUB_PROMPT_OPENED_STOP);`
        inp_publish(INP_PUB_PROMPT_OPENED_STOP);
    } // end of behavior for StopPrompt
}

static void STOPPROMPT_exit(InputResolutionSm* sm)
{
    sm->state_id = InputResolutionSm_StateId_PROMPT;
}

static void STOPPROMPT_enc0_press(InputResolutionSm* sm)
{
    bool consume_event = false;
    
    // StopPrompt behavior
    // uml: ENC0_PRESS / { inp_swallow(); inp_publish(INP_PUB_PROMPT_CONFIRMED_STOP); inp_issue(INP_CMD_STOP_SESSION); } TransitionTo(Consumed)
    {
        // Step 1: Exit states until we reach `Btn0Held` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, InputResolutionSm_StateId_BTN0HELD);
        
        // Step 2: Transition action: `inp_swallow(); inp_publish(INP_PUB_PROMPT_CONFIRMED_STOP); inp_issue(INP_CMD_STOP_SESSION);`.
        inp_swallow(); inp_publish(INP_PUB_PROMPT_CONFIRMED_STOP); inp_issue(INP_CMD_STOP_SESSION);
        
        // Step 3: Enter/move towards transition target `Consumed`.
        CONSUMED_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for StopPrompt
    
    // Check if event has been consumed before calling ancestor handler.
    if (!consume_event)
    {
        BTN0HELD_enc0_press(sm);
    }
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state NEUTRAL
////////////////////////////////////////////////////////////////////////////////

static void NEUTRAL_enter(InputResolutionSm* sm)
{
    sm->state_id = InputResolutionSm_StateId_NEUTRAL;
}

static void NEUTRAL_exit(InputResolutionSm* sm)
{
    sm->state_id = InputResolutionSm_StateId_ROOT;
}

static void NEUTRAL_btn0_press(InputResolutionSm* sm)
{
    // Neutral behavior
    // uml: BTN0_PRESS [!inp_session_hold_allowed()] / { inp_deliver(); }
    if (!inp_session_hold_allowed())
    {
        // Step 1: execute action `inp_deliver();`
        inp_deliver();
    } // end of behavior for Neutral
    
    // Neutral behavior
    // uml: BTN0_PRESS [inp_session_hold_allowed()] / { inp_swallow(); } TransitionTo(Pending)
    if (inp_session_hold_allowed())
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        NEUTRAL_exit(sm);
        
        // Step 2: Transition action: `inp_swallow();`.
        inp_swallow();
        
        // Step 3: Enter/move towards transition target `Pending`.
        BTN0HELD_enter(sm);
        PENDING_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for Neutral
    
    // No ancestor handles this event.
}

static void NEUTRAL_btn0_release(InputResolutionSm* sm)
{
    // Neutral behavior
    // uml: BTN0_RELEASE [inp_input_is_undelivered_release()] / { inp_swallow(); }
    if (inp_input_is_undelivered_release())
    {
        // Step 1: execute action `inp_swallow();`
        inp_swallow();
    } // end of behavior for Neutral
    
    // Neutral behavior
    // uml: BTN0_RELEASE [!inp_input_is_undelivered_release()] / { inp_deliver(); }
    if (!inp_input_is_undelivered_release())
    {
        // Step 1: execute action `inp_deliver();`
        inp_deliver();
    } // end of behavior for Neutral
    
    // No ancestor handles this event.
}

static void NEUTRAL_enc0_press(InputResolutionSm* sm)
{
    // Neutral behavior
    // uml: ENC0_PRESS / { inp_deliver(); }
    {
        // Step 1: execute action `inp_deliver();`
        inp_deliver();
    } // end of behavior for Neutral
    
    // No ancestor handles this event.
}

static void NEUTRAL_input(InputResolutionSm* sm)
{
    // Neutral behavior
    // uml: INPUT [inp_input_is_undelivered_release()] / { inp_swallow(); }
    if (inp_input_is_undelivered_release())
    {
        // Step 1: execute action `inp_swallow();`
        inp_swallow();
    } // end of behavior for Neutral
    
    // Neutral behavior
    // uml: INPUT [!inp_input_is_undelivered_release()] / { inp_deliver(); }
    if (!inp_input_is_undelivered_release())
    {
        // Step 1: execute action `inp_deliver();`
        inp_deliver();
    } // end of behavior for Neutral
    
    // No ancestor handles this event.
}

static void NEUTRAL_reconcile(InputResolutionSm* sm)
{
    // Neutral behavior
    // uml: RECONCILE / { inp_release_all(); }
    {
        // Step 1: execute action `inp_release_all();`
        inp_release_all();
    } // end of behavior for Neutral
    
    // No ancestor handles this event.
}

// Thread safe. This function can be disabled with `outputStateIdToStringFunction` setting.
char const * InputResolutionSm_state_id_to_string(InputResolutionSm_StateId id)
{
    switch (id)
    {
        case InputResolutionSm_StateId_ROOT: return "ROOT";
        case InputResolutionSm_StateId_BTN0HELD: return "BTN0HELD";
        case InputResolutionSm_StateId_CONSUMED: return "CONSUMED";
        case InputResolutionSm_StateId_PENDING: return "PENDING";
        case InputResolutionSm_StateId_PROMPT: return "PROMPT";
        case InputResolutionSm_StateId_STARTPROMPT: return "STARTPROMPT";
        case InputResolutionSm_StateId_STOPPROMPT: return "STOPPROMPT";
        case InputResolutionSm_StateId_NEUTRAL: return "NEUTRAL";
        default: return "?";
    }
}

// Thread safe. This function can be disabled with `outputEventIdToStringFunction` setting.
char const * InputResolutionSm_event_id_to_string(InputResolutionSm_EventId id)
{
    switch (id)
    {
        case InputResolutionSm_EventId_BTN0_PRESS: return "BTN0_PRESS";
        case InputResolutionSm_EventId_BTN0_RELEASE: return "BTN0_RELEASE";
        case InputResolutionSm_EventId_ENC0_PRESS: return "ENC0_PRESS";
        case InputResolutionSm_EventId_HOLD_THRESHOLD: return "HOLD_THRESHOLD";
        case InputResolutionSm_EventId_INPUT: return "INPUT";
        case InputResolutionSm_EventId_RECONCILE: return "RECONCILE";
        case InputResolutionSm_EventId_SESSION_CHANGED: return "SESSION_CHANGED";
        default: return "?";
    }
}

// Returns the parent state for a given state. Returns ROOT if input has no parent.
// Thread safe. This function can be disabled with `outputGetParentIdFunction` setting.
InputResolutionSm_StateId InputResolutionSm_get_parent_id(InputResolutionSm_StateId id)
{
    switch (id)
    {
        case InputResolutionSm_StateId_ROOT: return InputResolutionSm_StateId_ROOT;
        case InputResolutionSm_StateId_BTN0HELD: return InputResolutionSm_StateId_ROOT;
        case InputResolutionSm_StateId_CONSUMED: return InputResolutionSm_StateId_BTN0HELD;
        case InputResolutionSm_StateId_PENDING: return InputResolutionSm_StateId_BTN0HELD;
        case InputResolutionSm_StateId_PROMPT: return InputResolutionSm_StateId_BTN0HELD;
        case InputResolutionSm_StateId_STARTPROMPT: return InputResolutionSm_StateId_PROMPT;
        case InputResolutionSm_StateId_STOPPROMPT: return InputResolutionSm_StateId_PROMPT;
        case InputResolutionSm_StateId_NEUTRAL: return InputResolutionSm_StateId_ROOT;
        default: return InputResolutionSm_StateId_ROOT;
    }
}
