// Autogenerated with StateSmith 0.22.2+0c32be37bf4d4fee5499780a5ef37a7996c192f9.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

#include "RadioSm.h"
#include <stdbool.h> // required for `consume_event` flag
#include <string.h> // for memset
#include "radio_port.h"


// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(RadioSm* sm, RadioSm_StateId desired_state);

static void ROOT_enter(RadioSm* sm);

static void ROOT_ChoicePoint_TuneIssue__transition(RadioSm* sm);

static void ROOT_ChoicePoint_BandSwitch__transition(RadioSm* sm);

static void ROOT_ChoicePoint_NextCommand__transition(RadioSm* sm);

static void FAULTED_enter(RadioSm* sm);

static void FAULTED_exit(RadioSm* sm);

static void FAULTED_band(RadioSm* sm);

static void FAULTED_step(RadioSm* sm);

static void FAULTED_tune(RadioSm* sm);

static void OPERATIONAL_enter(RadioSm* sm);

static void OPERATIONAL_exit(RadioSm* sm);

static void OPERATIONAL_audio_fault(RadioSm* sm);

static void SETTLED_enter(RadioSm* sm);

static void SETTLED_exit(RadioSm* sm);

static void SETTLED_band(RadioSm* sm);

static void SETTLED_step(RadioSm* sm);

static void SETTLED_tune(RadioSm* sm);

static void TUNING_enter(RadioSm* sm);

static void TUNING_exit(RadioSm* sm);

static void TUNING_band(RadioSm* sm);

static void TUNING_step(RadioSm* sm);

static void TUNING_tune(RadioSm* sm);

static void TUNING_tune_done(RadioSm* sm);

static void TUNING_tune_failed(RadioSm* sm);

static void STOPPED_enter(RadioSm* sm);

static void STOPPED_exit(RadioSm* sm);

static void STOPPED_band(RadioSm* sm);

static void STOPPED_start_failed(RadioSm* sm);

static void STOPPED_start_ok(RadioSm* sm);

static void STOPPED_step(RadioSm* sm);

static void STOPPED_tune(RadioSm* sm);


// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void RadioSm_ctor(RadioSm* sm)
{
    memset(sm, 0, sizeof(*sm));
}

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void RadioSm_start(RadioSm* sm)
{
    ROOT_enter(sm);
    // ROOT behavior
    // uml: TransitionTo(ROOT.<InitialState>)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `ROOT.<InitialState>`.
        // ROOT.<InitialState> is a pseudo state and cannot have an `enter` trigger.
        
        // ROOT.<InitialState> behavior
        // uml: TransitionTo(Stopped)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `Stopped`.
            STOPPED_enter(sm);
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for ROOT.<InitialState>
    } // end of behavior for ROOT
}

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void RadioSm_dispatch_event(RadioSm* sm, RadioSm_EventId event_id)
{
    switch (sm->state_id)
    {
        // STATE: RadioSm
        case RadioSm_StateId_ROOT:
            // No events handled by this state (or its ancestors).
            break;
        
        // STATE: Faulted
        case RadioSm_StateId_FAULTED:
            switch (event_id)
            {
                case RadioSm_EventId_TUNE: FAULTED_tune(sm); break;
                case RadioSm_EventId_STEP: FAULTED_step(sm); break;
                case RadioSm_EventId_BAND: FAULTED_band(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: Operational
        case RadioSm_StateId_OPERATIONAL:
            switch (event_id)
            {
                case RadioSm_EventId_AUDIO_FAULT: OPERATIONAL_audio_fault(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: Settled
        case RadioSm_StateId_SETTLED:
            switch (event_id)
            {
                case RadioSm_EventId_TUNE: SETTLED_tune(sm); break;
                case RadioSm_EventId_STEP: SETTLED_step(sm); break;
                case RadioSm_EventId_BAND: SETTLED_band(sm); break;
                case RadioSm_EventId_AUDIO_FAULT: OPERATIONAL_audio_fault(sm); break; // First ancestor handler for this event
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: Tuning
        case RadioSm_StateId_TUNING:
            switch (event_id)
            {
                case RadioSm_EventId_TUNE: TUNING_tune(sm); break;
                case RadioSm_EventId_STEP: TUNING_step(sm); break;
                case RadioSm_EventId_BAND: TUNING_band(sm); break;
                case RadioSm_EventId_TUNE_DONE: TUNING_tune_done(sm); break;
                case RadioSm_EventId_TUNE_FAILED: TUNING_tune_failed(sm); break;
                case RadioSm_EventId_AUDIO_FAULT: OPERATIONAL_audio_fault(sm); break; // First ancestor handler for this event
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: Stopped
        case RadioSm_StateId_STOPPED:
            switch (event_id)
            {
                case RadioSm_EventId_TUNE: STOPPED_tune(sm); break;
                case RadioSm_EventId_STEP: STOPPED_step(sm); break;
                case RadioSm_EventId_BAND: STOPPED_band(sm); break;
                case RadioSm_EventId_START_OK: STOPPED_start_ok(sm); break;
                case RadioSm_EventId_START_FAILED: STOPPED_start_failed(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
    }
    
}

// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(RadioSm* sm, RadioSm_StateId desired_state)
{
    while (sm->state_id != desired_state)
    {
        switch (sm->state_id)
        {
            case RadioSm_StateId_FAULTED: FAULTED_exit(sm); break;
            
            case RadioSm_StateId_OPERATIONAL: OPERATIONAL_exit(sm); break;
            
            case RadioSm_StateId_SETTLED: SETTLED_exit(sm); break;
            
            case RadioSm_StateId_TUNING: TUNING_exit(sm); break;
            
            case RadioSm_StateId_STOPPED: STOPPED_exit(sm); break;
            
            default: return;  // Just to be safe. Prevents infinite loop if state ID memory is somehow corrupted.
        }
    }
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state ROOT
////////////////////////////////////////////////////////////////////////////////

static void ROOT_enter(RadioSm* sm)
{
    sm->state_id = RadioSm_StateId_ROOT;
}

static void ROOT_ChoicePoint_TuneIssue__transition(RadioSm* sm)
{
    // ROOT.<ChoicePoint>(TuneIssue) behavior
    // uml: [rad_tune_issued()] / { rad_publish(RAD_PUB_TUNE_STARTED); } TransitionTo(Tuning)
    if (rad_tune_issued())
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
        
        // Step 2: Transition action: `rad_publish(RAD_PUB_TUNE_STARTED);`.
        rad_publish(RAD_PUB_TUNE_STARTED);
        
        // Step 3: Enter/move towards transition target `Tuning`.
        OPERATIONAL_enter(sm);
        TUNING_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for ROOT.<ChoicePoint>(TuneIssue)
    
    // ROOT.<ChoicePoint>(TuneIssue) behavior
    // uml: / { rad_publish(RAD_PUB_TUNE_FAILED); } TransitionTo(Settled)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
        
        // Step 2: Transition action: `rad_publish(RAD_PUB_TUNE_FAILED);`.
        rad_publish(RAD_PUB_TUNE_FAILED);
        
        // Step 3: Enter/move towards transition target `Settled`.
        OPERATIONAL_enter(sm);
        SETTLED_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for ROOT.<ChoicePoint>(TuneIssue)
}

static void ROOT_ChoicePoint_BandSwitch__transition(RadioSm* sm)
{
    // ROOT.<ChoicePoint>(BandSwitch) behavior
    // uml: [rad_band_switched()] / { rad_publish(RAD_PUB_BAND_CHANGED); } TransitionTo(Settled)
    if (rad_band_switched())
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
        
        // Step 2: Transition action: `rad_publish(RAD_PUB_BAND_CHANGED);`.
        rad_publish(RAD_PUB_BAND_CHANGED);
        
        // Step 3: Enter/move towards transition target `Settled`.
        OPERATIONAL_enter(sm);
        SETTLED_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for ROOT.<ChoicePoint>(BandSwitch)
    
    // ROOT.<ChoicePoint>(BandSwitch) behavior
    // uml: / { rad_publish(RAD_PUB_FAULT_BAND); } TransitionTo(Faulted)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
        
        // Step 2: Transition action: `rad_publish(RAD_PUB_FAULT_BAND);`.
        rad_publish(RAD_PUB_FAULT_BAND);
        
        // Step 3: Enter/move towards transition target `Faulted`.
        FAULTED_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for ROOT.<ChoicePoint>(BandSwitch)
}

static void ROOT_ChoicePoint_NextCommand__transition(RadioSm* sm)
{
    // ROOT.<ChoicePoint>(NextCommand) behavior
    // uml: [rad_pending_is_tune()] / { rad_begin_pending(); } TransitionTo(ROOT.<ChoicePoint>(TuneIssue))
    if (rad_pending_is_tune())
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
        
        // Step 2: Transition action: `rad_begin_pending();`.
        rad_begin_pending();
        
        // Step 3: Enter/move towards transition target `ROOT.<ChoicePoint>(TuneIssue)`.
        // ROOT.<ChoicePoint>(TuneIssue) is a pseudo state and cannot have an `enter` trigger.
        
        // Finish transition by calling pseudo state transition function.
        ROOT_ChoicePoint_TuneIssue__transition(sm);
        return; // event processing immediately stops when a transition finishes. No other behaviors for this state are checked.
    } // end of behavior for ROOT.<ChoicePoint>(NextCommand)
    
    // ROOT.<ChoicePoint>(NextCommand) behavior
    // uml: [rad_pending_is_band()] / { rad_switch_band_pending(); } TransitionTo(ROOT.<ChoicePoint>(BandSwitch))
    if (rad_pending_is_band())
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
        
        // Step 2: Transition action: `rad_switch_band_pending();`.
        rad_switch_band_pending();
        
        // Step 3: Enter/move towards transition target `ROOT.<ChoicePoint>(BandSwitch)`.
        // ROOT.<ChoicePoint>(BandSwitch) is a pseudo state and cannot have an `enter` trigger.
        
        // Finish transition by calling pseudo state transition function.
        ROOT_ChoicePoint_BandSwitch__transition(sm);
        return; // event processing immediately stops when a transition finishes. No other behaviors for this state are checked.
    } // end of behavior for ROOT.<ChoicePoint>(NextCommand)
    
    // ROOT.<ChoicePoint>(NextCommand) behavior
    // uml: TransitionTo(Settled)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `Settled`.
        OPERATIONAL_enter(sm);
        SETTLED_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for ROOT.<ChoicePoint>(NextCommand)
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state FAULTED
////////////////////////////////////////////////////////////////////////////////

static void FAULTED_enter(RadioSm* sm)
{
    sm->state_id = RadioSm_StateId_FAULTED;
}

static void FAULTED_exit(RadioSm* sm)
{
    sm->state_id = RadioSm_StateId_ROOT;
}

static void FAULTED_band(RadioSm* sm)
{
    // Faulted behavior
    // uml: BAND / { rad_reject(RAD_REJECT_UNAVAILABLE); }
    {
        // Step 1: execute action `rad_reject(RAD_REJECT_UNAVAILABLE);`
        rad_reject(RAD_REJECT_UNAVAILABLE);
    } // end of behavior for Faulted
    
    // No ancestor handles this event.
}

static void FAULTED_step(RadioSm* sm)
{
    // Faulted behavior
    // uml: STEP / { rad_reject(RAD_REJECT_UNAVAILABLE); }
    {
        // Step 1: execute action `rad_reject(RAD_REJECT_UNAVAILABLE);`
        rad_reject(RAD_REJECT_UNAVAILABLE);
    } // end of behavior for Faulted
    
    // No ancestor handles this event.
}

static void FAULTED_tune(RadioSm* sm)
{
    // Faulted behavior
    // uml: TUNE / { rad_reject(RAD_REJECT_UNAVAILABLE); }
    {
        // Step 1: execute action `rad_reject(RAD_REJECT_UNAVAILABLE);`
        rad_reject(RAD_REJECT_UNAVAILABLE);
    } // end of behavior for Faulted
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state OPERATIONAL
////////////////////////////////////////////////////////////////////////////////

static void OPERATIONAL_enter(RadioSm* sm)
{
    sm->state_id = RadioSm_StateId_OPERATIONAL;
}

static void OPERATIONAL_exit(RadioSm* sm)
{
    sm->state_id = RadioSm_StateId_ROOT;
}

static void OPERATIONAL_audio_fault(RadioSm* sm)
{
    // Operational behavior
    // uml: AUDIO_FAULT / { rad_abandon(); rad_publish(RAD_PUB_FAULT_AUDIO); } TransitionTo(Faulted)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, RadioSm_StateId_ROOT);
        
        // Step 2: Transition action: `rad_abandon(); rad_publish(RAD_PUB_FAULT_AUDIO);`.
        rad_abandon(); rad_publish(RAD_PUB_FAULT_AUDIO);
        
        // Step 3: Enter/move towards transition target `Faulted`.
        FAULTED_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for Operational
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state SETTLED
////////////////////////////////////////////////////////////////////////////////

static void SETTLED_enter(RadioSm* sm)
{
    sm->state_id = RadioSm_StateId_SETTLED;
}

static void SETTLED_exit(RadioSm* sm)
{
    sm->state_id = RadioSm_StateId_OPERATIONAL;
}

static void SETTLED_band(RadioSm* sm)
{
    // Settled behavior
    // uml: BAND / { rad_switch_band_request(); } TransitionTo(ROOT.<ChoicePoint>(BandSwitch))
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, RadioSm_StateId_ROOT);
        
        // Step 2: Transition action: `rad_switch_band_request();`.
        rad_switch_band_request();
        
        // Step 3: Enter/move towards transition target `ROOT.<ChoicePoint>(BandSwitch)`.
        // ROOT.<ChoicePoint>(BandSwitch) is a pseudo state and cannot have an `enter` trigger.
        
        // Finish transition by calling pseudo state transition function.
        ROOT_ChoicePoint_BandSwitch__transition(sm);
        return; // event processing immediately stops when a transition finishes. No other behaviors for this state are checked.
    } // end of behavior for Settled
    
    // No ancestor handles this event.
}

static void SETTLED_step(RadioSm* sm)
{
    // Settled behavior
    // uml: STEP / { rad_begin_request(); } TransitionTo(ROOT.<ChoicePoint>(TuneIssue))
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, RadioSm_StateId_ROOT);
        
        // Step 2: Transition action: `rad_begin_request();`.
        rad_begin_request();
        
        // Step 3: Enter/move towards transition target `ROOT.<ChoicePoint>(TuneIssue)`.
        // ROOT.<ChoicePoint>(TuneIssue) is a pseudo state and cannot have an `enter` trigger.
        
        // Finish transition by calling pseudo state transition function.
        ROOT_ChoicePoint_TuneIssue__transition(sm);
        return; // event processing immediately stops when a transition finishes. No other behaviors for this state are checked.
    } // end of behavior for Settled
    
    // No ancestor handles this event.
}

static void SETTLED_tune(RadioSm* sm)
{
    // Settled behavior
    // uml: TUNE [!rad_request_in_range()] / { rad_reject(RAD_REJECT_RANGE); }
    if (!rad_request_in_range())
    {
        // Step 1: execute action `rad_reject(RAD_REJECT_RANGE);`
        rad_reject(RAD_REJECT_RANGE);
    } // end of behavior for Settled
    
    // Settled behavior
    // uml: TUNE [rad_request_in_range()] / { rad_begin_request(); } TransitionTo(ROOT.<ChoicePoint>(TuneIssue))
    if (rad_request_in_range())
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, RadioSm_StateId_ROOT);
        
        // Step 2: Transition action: `rad_begin_request();`.
        rad_begin_request();
        
        // Step 3: Enter/move towards transition target `ROOT.<ChoicePoint>(TuneIssue)`.
        // ROOT.<ChoicePoint>(TuneIssue) is a pseudo state and cannot have an `enter` trigger.
        
        // Finish transition by calling pseudo state transition function.
        ROOT_ChoicePoint_TuneIssue__transition(sm);
        return; // event processing immediately stops when a transition finishes. No other behaviors for this state are checked.
    } // end of behavior for Settled
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state TUNING
////////////////////////////////////////////////////////////////////////////////

static void TUNING_enter(RadioSm* sm)
{
    sm->state_id = RadioSm_StateId_TUNING;
}

static void TUNING_exit(RadioSm* sm)
{
    sm->state_id = RadioSm_StateId_OPERATIONAL;
}

static void TUNING_band(RadioSm* sm)
{
    // Tuning behavior
    // uml: BAND / { rad_hold_request(); }
    {
        // Step 1: execute action `rad_hold_request();`
        rad_hold_request();
    } // end of behavior for Tuning
    
    // No ancestor handles this event.
}

static void TUNING_step(RadioSm* sm)
{
    // Tuning behavior
    // uml: STEP / { rad_hold_request(); }
    {
        // Step 1: execute action `rad_hold_request();`
        rad_hold_request();
    } // end of behavior for Tuning
    
    // No ancestor handles this event.
}

static void TUNING_tune(RadioSm* sm)
{
    // Tuning behavior
    // uml: TUNE [rad_request_in_range()] / { rad_hold_request(); }
    if (rad_request_in_range())
    {
        // Step 1: execute action `rad_hold_request();`
        rad_hold_request();
    } // end of behavior for Tuning
    
    // Tuning behavior
    // uml: TUNE [!rad_request_in_range()] / { rad_reject(RAD_REJECT_RANGE); }
    if (!rad_request_in_range())
    {
        // Step 1: execute action `rad_reject(RAD_REJECT_RANGE);`
        rad_reject(RAD_REJECT_RANGE);
    } // end of behavior for Tuning
    
    // No ancestor handles this event.
}

static void TUNING_tune_done(RadioSm* sm)
{
    // Tuning behavior
    // uml: TUNE_DONE / { rad_publish(RAD_PUB_TUNED); } TransitionTo(ROOT.<ChoicePoint>(NextCommand))
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, RadioSm_StateId_ROOT);
        
        // Step 2: Transition action: `rad_publish(RAD_PUB_TUNED);`.
        rad_publish(RAD_PUB_TUNED);
        
        // Step 3: Enter/move towards transition target `ROOT.<ChoicePoint>(NextCommand)`.
        // ROOT.<ChoicePoint>(NextCommand) is a pseudo state and cannot have an `enter` trigger.
        
        // Finish transition by calling pseudo state transition function.
        ROOT_ChoicePoint_NextCommand__transition(sm);
        return; // event processing immediately stops when a transition finishes. No other behaviors for this state are checked.
    } // end of behavior for Tuning
    
    // No ancestor handles this event.
}

static void TUNING_tune_failed(RadioSm* sm)
{
    // Tuning behavior
    // uml: TUNE_FAILED / { rad_publish(RAD_PUB_TUNE_FAILED); } TransitionTo(ROOT.<ChoicePoint>(NextCommand))
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, RadioSm_StateId_ROOT);
        
        // Step 2: Transition action: `rad_publish(RAD_PUB_TUNE_FAILED);`.
        rad_publish(RAD_PUB_TUNE_FAILED);
        
        // Step 3: Enter/move towards transition target `ROOT.<ChoicePoint>(NextCommand)`.
        // ROOT.<ChoicePoint>(NextCommand) is a pseudo state and cannot have an `enter` trigger.
        
        // Finish transition by calling pseudo state transition function.
        ROOT_ChoicePoint_NextCommand__transition(sm);
        return; // event processing immediately stops when a transition finishes. No other behaviors for this state are checked.
    } // end of behavior for Tuning
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state STOPPED
////////////////////////////////////////////////////////////////////////////////

static void STOPPED_enter(RadioSm* sm)
{
    sm->state_id = RadioSm_StateId_STOPPED;
}

static void STOPPED_exit(RadioSm* sm)
{
    sm->state_id = RadioSm_StateId_ROOT;
}

static void STOPPED_band(RadioSm* sm)
{
    // Stopped behavior
    // uml: BAND / { rad_reject(RAD_REJECT_UNAVAILABLE); }
    {
        // Step 1: execute action `rad_reject(RAD_REJECT_UNAVAILABLE);`
        rad_reject(RAD_REJECT_UNAVAILABLE);
    } // end of behavior for Stopped
    
    // No ancestor handles this event.
}

static void STOPPED_start_failed(RadioSm* sm)
{
    // Stopped behavior
    // uml: START_FAILED / { rad_publish(RAD_PUB_FAULT_START); } TransitionTo(Faulted)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        STOPPED_exit(sm);
        
        // Step 2: Transition action: `rad_publish(RAD_PUB_FAULT_START);`.
        rad_publish(RAD_PUB_FAULT_START);
        
        // Step 3: Enter/move towards transition target `Faulted`.
        FAULTED_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for Stopped
    
    // No ancestor handles this event.
}

static void STOPPED_start_ok(RadioSm* sm)
{
    // Stopped behavior
    // uml: START_OK / { rad_publish(RAD_PUB_STARTED); } TransitionTo(Settled)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        STOPPED_exit(sm);
        
        // Step 2: Transition action: `rad_publish(RAD_PUB_STARTED);`.
        rad_publish(RAD_PUB_STARTED);
        
        // Step 3: Enter/move towards transition target `Settled`.
        OPERATIONAL_enter(sm);
        SETTLED_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for Stopped
    
    // No ancestor handles this event.
}

static void STOPPED_step(RadioSm* sm)
{
    // Stopped behavior
    // uml: STEP / { rad_reject(RAD_REJECT_UNAVAILABLE); }
    {
        // Step 1: execute action `rad_reject(RAD_REJECT_UNAVAILABLE);`
        rad_reject(RAD_REJECT_UNAVAILABLE);
    } // end of behavior for Stopped
    
    // No ancestor handles this event.
}

static void STOPPED_tune(RadioSm* sm)
{
    // Stopped behavior
    // uml: TUNE / { rad_reject(RAD_REJECT_UNAVAILABLE); }
    {
        // Step 1: execute action `rad_reject(RAD_REJECT_UNAVAILABLE);`
        rad_reject(RAD_REJECT_UNAVAILABLE);
    } // end of behavior for Stopped
    
    // No ancestor handles this event.
}

// Thread safe. This function can be disabled with `outputStateIdToStringFunction` setting.
char const * RadioSm_state_id_to_string(RadioSm_StateId id)
{
    switch (id)
    {
        case RadioSm_StateId_ROOT: return "ROOT";
        case RadioSm_StateId_FAULTED: return "FAULTED";
        case RadioSm_StateId_OPERATIONAL: return "OPERATIONAL";
        case RadioSm_StateId_SETTLED: return "SETTLED";
        case RadioSm_StateId_TUNING: return "TUNING";
        case RadioSm_StateId_STOPPED: return "STOPPED";
        default: return "?";
    }
}

// Thread safe. This function can be disabled with `outputEventIdToStringFunction` setting.
char const * RadioSm_event_id_to_string(RadioSm_EventId id)
{
    switch (id)
    {
        case RadioSm_EventId_AUDIO_FAULT: return "AUDIO_FAULT";
        case RadioSm_EventId_BAND: return "BAND";
        case RadioSm_EventId_START_FAILED: return "START_FAILED";
        case RadioSm_EventId_START_OK: return "START_OK";
        case RadioSm_EventId_STEP: return "STEP";
        case RadioSm_EventId_TUNE: return "TUNE";
        case RadioSm_EventId_TUNE_DONE: return "TUNE_DONE";
        case RadioSm_EventId_TUNE_FAILED: return "TUNE_FAILED";
        default: return "?";
    }
}

// Returns the parent state for a given state. Returns ROOT if input has no parent.
// Thread safe. This function can be disabled with `outputGetParentIdFunction` setting.
RadioSm_StateId RadioSm_get_parent_id(RadioSm_StateId id)
{
    switch (id)
    {
        case RadioSm_StateId_ROOT: return RadioSm_StateId_ROOT;
        case RadioSm_StateId_FAULTED: return RadioSm_StateId_ROOT;
        case RadioSm_StateId_OPERATIONAL: return RadioSm_StateId_ROOT;
        case RadioSm_StateId_SETTLED: return RadioSm_StateId_OPERATIONAL;
        case RadioSm_StateId_TUNING: return RadioSm_StateId_OPERATIONAL;
        case RadioSm_StateId_STOPPED: return RadioSm_StateId_ROOT;
        default: return RadioSm_StateId_ROOT;
    }
}
