// Autogenerated with StateSmith 0.22.2+0c32be37bf4d4fee5499780a5ef37a7996c192f9.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

#ifndef SPOOKY_RADIO_SM_H
#define SPOOKY_RADIO_SM_H
#include <stdint.h>

typedef enum RadioSm_EventId
{
    RadioSm_EventId_AUDIO_FAULT = 0,
    RadioSm_EventId_BAND = 1,
    RadioSm_EventId_START_FAILED = 2,
    RadioSm_EventId_START_OK = 3,
    RadioSm_EventId_STEP = 4,
    RadioSm_EventId_TUNE = 5,
    RadioSm_EventId_TUNE_DONE = 6,
    RadioSm_EventId_TUNE_FAILED = 7
} RadioSm_EventId;

#define RadioSm_EventIdCount (8)

typedef enum RadioSm_StateId
{
    RadioSm_StateId_ROOT = 0,
    RadioSm_StateId_FAULTED = 1,
    RadioSm_StateId_OPERATIONAL = 2,
    RadioSm_StateId_SETTLED = 3,
    RadioSm_StateId_TUNING = 4,
    RadioSm_StateId_STOPPED = 5
} RadioSm_StateId;

#define RadioSm_StateIdCount (6)

// Subtree meta data generation can be disabled in settings.
// Details: https://github.com/StateSmith/StateSmith/issues/538
#define RadioSm_ROOT_SubtreeEndId (5)  // State 'RadioSm' subtree extends from itself (id: 0) to state 'Stopped' (id: 5)
#define RadioSm_FAULTED_SubtreeEndId (1)  // State 'Faulted' subtree extends from itself (id: 1) to state 'Faulted' (id: 1)
#define RadioSm_OPERATIONAL_SubtreeEndId (4)  // State 'Operational' subtree extends from itself (id: 2) to state 'Tuning' (id: 4)
#define RadioSm_SETTLED_SubtreeEndId (3)  // State 'Settled' subtree extends from itself (id: 3) to state 'Settled' (id: 3)
#define RadioSm_TUNING_SubtreeEndId (4)  // State 'Tuning' subtree extends from itself (id: 4) to state 'Tuning' (id: 4)
#define RadioSm_STOPPED_SubtreeEndId (5)  // State 'Stopped' subtree extends from itself (id: 5) to state 'Stopped' (id: 5)


// Generated state machine
// forward declaration
typedef struct RadioSm RadioSm;

// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void RadioSm_ctor(RadioSm* sm);

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void RadioSm_start(RadioSm* sm);

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void RadioSm_dispatch_event(RadioSm* sm, RadioSm_EventId event_id);

// Thread safe. This function can be disabled with `outputStateIdToStringFunction` setting.
char const * RadioSm_state_id_to_string(RadioSm_StateId id);

// Thread safe. This function can be disabled with `outputEventIdToStringFunction` setting.
char const * RadioSm_event_id_to_string(RadioSm_EventId id);

// Returns the parent state for a given state. Returns ROOT if input has no parent.
// Thread safe. This function can be disabled with `outputGetParentIdFunction` setting.
RadioSm_StateId RadioSm_get_parent_id(RadioSm_StateId id);

// Generated state machine
struct RadioSm
{
    // Used internally by state machine. Feel free to inspect, but don't modify.
    RadioSm_StateId state_id;
};

#endif // SPOOKY_RADIO_SM_H
