// Autogenerated with StateSmith 0.22.2+0c32be37bf4d4fee5499780a5ef37a7996c192f9.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

#include "SessionSm.h"
#include <stdbool.h> // required for `consume_event` flag
#include <string.h> // for memset
#include "session_port.h"


// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(SessionSm* sm, SessionSm_StateId desired_state);

static void ROOT_enter(SessionSm* sm);

static void ROOT_ChoicePoint_FinalizeResult__transition(SessionSm* sm);

static void ACTIVE_enter(SessionSm* sm);

static void ACTIVE_exit(SessionSm* sm);

static void ACTIVE_capture_fault(SessionSm* sm);

static void ACTIVE_start(SessionSm* sm);

static void FINALIZING_enter(SessionSm* sm);

static void FINALIZING_exit(SessionSm* sm);

static void FINALIZING_block_written(SessionSm* sm);

static void FINALIZING_stop(SessionSm* sm);

static void RECORDING_enter(SessionSm* sm);

static void RECORDING_exit(SessionSm* sm);

static void RECORDING_block_written(SessionSm* sm);

static void RECORDING_stop(SessionSm* sm);

static void IDLE_enter(SessionSm* sm);

static void IDLE_exit(SessionSm* sm);

static void IDLE_start(SessionSm* sm);

static void IDLE_stop(SessionSm* sm);


// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void SessionSm_ctor(SessionSm* sm)
{
    memset(sm, 0, sizeof(*sm));
}

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void SessionSm_start(SessionSm* sm)
{
    ROOT_enter(sm);
    // ROOT behavior
    // uml: TransitionTo(ROOT.<InitialState>)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `ROOT.<InitialState>`.
        // ROOT.<InitialState> is a pseudo state and cannot have an `enter` trigger.
        
        // ROOT.<InitialState> behavior
        // uml: TransitionTo(Idle)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `Idle`.
            IDLE_enter(sm);
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for ROOT.<InitialState>
    } // end of behavior for ROOT
}

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void SessionSm_dispatch_event(SessionSm* sm, SessionSm_EventId event_id)
{
    switch (sm->state_id)
    {
        // STATE: SessionSm
        case SessionSm_StateId_ROOT:
            // No events handled by this state (or its ancestors).
            break;
        
        // STATE: Active
        case SessionSm_StateId_ACTIVE:
            switch (event_id)
            {
                case SessionSm_EventId_START: ACTIVE_start(sm); break;
                case SessionSm_EventId_CAPTURE_FAULT: ACTIVE_capture_fault(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: Finalizing
        case SessionSm_StateId_FINALIZING:
            switch (event_id)
            {
                case SessionSm_EventId_STOP: FINALIZING_stop(sm); break;
                case SessionSm_EventId_BLOCK_WRITTEN: FINALIZING_block_written(sm); break;
                case SessionSm_EventId_START: ACTIVE_start(sm); break; // First ancestor handler for this event
                case SessionSm_EventId_CAPTURE_FAULT: ACTIVE_capture_fault(sm); break; // First ancestor handler for this event
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: Recording
        case SessionSm_StateId_RECORDING:
            switch (event_id)
            {
                case SessionSm_EventId_STOP: RECORDING_stop(sm); break;
                case SessionSm_EventId_BLOCK_WRITTEN: RECORDING_block_written(sm); break;
                case SessionSm_EventId_START: ACTIVE_start(sm); break; // First ancestor handler for this event
                case SessionSm_EventId_CAPTURE_FAULT: ACTIVE_capture_fault(sm); break; // First ancestor handler for this event
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: Idle
        case SessionSm_StateId_IDLE:
            switch (event_id)
            {
                case SessionSm_EventId_START: IDLE_start(sm); break;
                case SessionSm_EventId_STOP: IDLE_stop(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
    }
    
}

// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(SessionSm* sm, SessionSm_StateId desired_state)
{
    while (sm->state_id != desired_state)
    {
        switch (sm->state_id)
        {
            case SessionSm_StateId_ACTIVE: ACTIVE_exit(sm); break;
            
            case SessionSm_StateId_FINALIZING: FINALIZING_exit(sm); break;
            
            case SessionSm_StateId_RECORDING: RECORDING_exit(sm); break;
            
            case SessionSm_StateId_IDLE: IDLE_exit(sm); break;
            
            default: return;  // Just to be safe. Prevents infinite loop if state ID memory is somehow corrupted.
        }
    }
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state ROOT
////////////////////////////////////////////////////////////////////////////////

static void ROOT_enter(SessionSm* sm)
{
    sm->state_id = SessionSm_StateId_ROOT;
}

static void ROOT_ChoicePoint_FinalizeResult__transition(SessionSm* sm)
{
    // ROOT.<ChoicePoint>(FinalizeResult) behavior
    // uml: [ses_finalize_ok()] / { ses_publish(SES_PUB_RECORDING_COMPLETED); } TransitionTo(Idle)
    if (ses_finalize_ok())
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
        
        // Step 2: Transition action: `ses_publish(SES_PUB_RECORDING_COMPLETED);`.
        ses_publish(SES_PUB_RECORDING_COMPLETED);
        
        // Step 3: Enter/move towards transition target `Idle`.
        IDLE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for ROOT.<ChoicePoint>(FinalizeResult)
    
    // ROOT.<ChoicePoint>(FinalizeResult) behavior
    // uml: else / { ses_publish(SES_PUB_RECORDING_ABORTED); } TransitionTo(Idle)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
        
        // Step 2: Transition action: `ses_publish(SES_PUB_RECORDING_ABORTED);`.
        ses_publish(SES_PUB_RECORDING_ABORTED);
        
        // Step 3: Enter/move towards transition target `Idle`.
        IDLE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for ROOT.<ChoicePoint>(FinalizeResult)
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state ACTIVE
////////////////////////////////////////////////////////////////////////////////

static void ACTIVE_enter(SessionSm* sm)
{
    sm->state_id = SessionSm_StateId_ACTIVE;
}

static void ACTIVE_exit(SessionSm* sm)
{
    sm->state_id = SessionSm_StateId_ROOT;
}

static void ACTIVE_capture_fault(SessionSm* sm)
{
    // Active behavior
    // uml: CAPTURE_FAULT / { ses_stop_capture(); ses_finalize_file(); ses_publish(SES_PUB_RECORDING_ABORTED); } TransitionTo(Idle)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, SessionSm_StateId_ROOT);
        
        // Step 2: Transition action: `ses_stop_capture(); ses_finalize_file(); ses_publish(SES_PUB_RECORDING_ABORTED);`.
        ses_stop_capture(); ses_finalize_file(); ses_publish(SES_PUB_RECORDING_ABORTED);
        
        // Step 3: Enter/move towards transition target `Idle`.
        IDLE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for Active
    
    // No ancestor handles this event.
}

static void ACTIVE_start(SessionSm* sm)
{
    // Active behavior
    // uml: START / { ses_publish(SES_PUB_RECORDING_REJECTED); }
    {
        // Step 1: execute action `ses_publish(SES_PUB_RECORDING_REJECTED);`
        ses_publish(SES_PUB_RECORDING_REJECTED);
    } // end of behavior for Active
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state FINALIZING
////////////////////////////////////////////////////////////////////////////////

static void FINALIZING_enter(SessionSm* sm)
{
    sm->state_id = SessionSm_StateId_FINALIZING;
    
    // Finalizing behavior
    // uml: enter / { ses_state_changed(); }
    {
        // Step 1: execute action `ses_state_changed();`
        ses_state_changed();
    } // end of behavior for Finalizing
}

static void FINALIZING_exit(SessionSm* sm)
{
    sm->state_id = SessionSm_StateId_ACTIVE;
}

static void FINALIZING_block_written(SessionSm* sm)
{
    // Finalizing behavior
    // uml: BLOCK_WRITTEN / { ses_stop_capture(); ses_finalize_file(); } TransitionTo(ROOT.<ChoicePoint>(FinalizeResult))
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, SessionSm_StateId_ROOT);
        
        // Step 2: Transition action: `ses_stop_capture(); ses_finalize_file();`.
        ses_stop_capture(); ses_finalize_file();
        
        // Step 3: Enter/move towards transition target `ROOT.<ChoicePoint>(FinalizeResult)`.
        // ROOT.<ChoicePoint>(FinalizeResult) is a pseudo state and cannot have an `enter` trigger.
        
        // Finish transition by calling pseudo state transition function.
        ROOT_ChoicePoint_FinalizeResult__transition(sm);
        return; // event processing immediately stops when a transition finishes. No other behaviors for this state are checked.
    } // end of behavior for Finalizing
    
    // No ancestor handles this event.
}

static void FINALIZING_stop(SessionSm* sm)
{
    // Finalizing behavior
    // uml: STOP / { ses_publish(SES_PUB_RECORDING_STOPPING); }
    {
        // Step 1: execute action `ses_publish(SES_PUB_RECORDING_STOPPING);`
        ses_publish(SES_PUB_RECORDING_STOPPING);
    } // end of behavior for Finalizing
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state RECORDING
////////////////////////////////////////////////////////////////////////////////

static void RECORDING_enter(SessionSm* sm)
{
    sm->state_id = SessionSm_StateId_RECORDING;
    
    // Recording behavior
    // uml: enter / { ses_state_changed(); }
    {
        // Step 1: execute action `ses_state_changed();`
        ses_state_changed();
    } // end of behavior for Recording
}

static void RECORDING_exit(SessionSm* sm)
{
    sm->state_id = SessionSm_StateId_ACTIVE;
}

static void RECORDING_block_written(SessionSm* sm)
{
    // Recording behavior
    // uml: BLOCK_WRITTEN [ses_target_reached()] / { ses_stop_capture(); ses_finalize_file(); } TransitionTo(ROOT.<ChoicePoint>(FinalizeResult))
    if (ses_target_reached())
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, SessionSm_StateId_ROOT);
        
        // Step 2: Transition action: `ses_stop_capture(); ses_finalize_file();`.
        ses_stop_capture(); ses_finalize_file();
        
        // Step 3: Enter/move towards transition target `ROOT.<ChoicePoint>(FinalizeResult)`.
        // ROOT.<ChoicePoint>(FinalizeResult) is a pseudo state and cannot have an `enter` trigger.
        
        // Finish transition by calling pseudo state transition function.
        ROOT_ChoicePoint_FinalizeResult__transition(sm);
        return; // event processing immediately stops when a transition finishes. No other behaviors for this state are checked.
    } // end of behavior for Recording
    
    // No ancestor handles this event.
}

static void RECORDING_stop(SessionSm* sm)
{
    // Recording behavior
    // uml: STOP / { ses_request_stop(); ses_publish(SES_PUB_RECORDING_STOPPING); } TransitionTo(Finalizing)
    {
        // Step 1: Exit states until we reach `Active` state (Least Common Ancestor for transition).
        RECORDING_exit(sm);
        
        // Step 2: Transition action: `ses_request_stop(); ses_publish(SES_PUB_RECORDING_STOPPING);`.
        ses_request_stop(); ses_publish(SES_PUB_RECORDING_STOPPING);
        
        // Step 3: Enter/move towards transition target `Finalizing`.
        FINALIZING_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for Recording
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state IDLE
////////////////////////////////////////////////////////////////////////////////

static void IDLE_enter(SessionSm* sm)
{
    sm->state_id = SessionSm_StateId_IDLE;
    
    // Idle behavior
    // uml: enter / { ses_state_changed(); }
    {
        // Step 1: execute action `ses_state_changed();`
        ses_state_changed();
    } // end of behavior for Idle
}

static void IDLE_exit(SessionSm* sm)
{
    sm->state_id = SessionSm_StateId_ROOT;
}

static void IDLE_start(SessionSm* sm)
{
    // Idle behavior
    // uml: START [!ses_can_start()] / { ses_publish(SES_PUB_RECORDING_REJECTED); }
    if (!ses_can_start())
    {
        // Step 1: execute action `ses_publish(SES_PUB_RECORDING_REJECTED);`
        ses_publish(SES_PUB_RECORDING_REJECTED);
    } // end of behavior for Idle
    
    // Idle behavior
    // uml: START [ses_can_start()] / { ses_open_file(); } TransitionTo(ROOT.<ChoicePoint>(OpenResult))
    if (ses_can_start())
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        IDLE_exit(sm);
        
        // Step 2: Transition action: `ses_open_file();`.
        ses_open_file();
        
        // Step 3: Enter/move towards transition target `ROOT.<ChoicePoint>(OpenResult)`.
        // ROOT.<ChoicePoint>(OpenResult) is a pseudo state and cannot have an `enter` trigger.
        
        // ROOT.<ChoicePoint>(OpenResult) behavior
        // uml: [!ses_file_opened()] / { ses_publish(SES_PUB_RECORDING_REJECTED); } TransitionTo(Idle)
        if (!ses_file_opened())
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
            
            // Step 2: Transition action: `ses_publish(SES_PUB_RECORDING_REJECTED);`.
            ses_publish(SES_PUB_RECORDING_REJECTED);
            
            // Step 3: Enter/move towards transition target `Idle`.
            IDLE_enter(sm);
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for ROOT.<ChoicePoint>(OpenResult)
        
        // ROOT.<ChoicePoint>(OpenResult) behavior
        // uml: else / { ses_start_capture(); } TransitionTo(ROOT.<ChoicePoint>(CaptureResult))
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
            
            // Step 2: Transition action: `ses_start_capture();`.
            ses_start_capture();
            
            // Step 3: Enter/move towards transition target `ROOT.<ChoicePoint>(CaptureResult)`.
            // ROOT.<ChoicePoint>(CaptureResult) is a pseudo state and cannot have an `enter` trigger.
            
            // ROOT.<ChoicePoint>(CaptureResult) behavior
            // uml: [ses_capture_started()] / { ses_publish(SES_PUB_RECORDING_STARTED); } TransitionTo(Recording)
            if (ses_capture_started())
            {
                // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
                
                // Step 2: Transition action: `ses_publish(SES_PUB_RECORDING_STARTED);`.
                ses_publish(SES_PUB_RECORDING_STARTED);
                
                // Step 3: Enter/move towards transition target `Recording`.
                ACTIVE_enter(sm);
                RECORDING_enter(sm);
                
                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for ROOT.<ChoicePoint>(CaptureResult)
            
            // ROOT.<ChoicePoint>(CaptureResult) behavior
            // uml: else / { ses_finalize_file(); ses_publish(SES_PUB_RECORDING_ABORTED); } TransitionTo(Idle)
            {
                // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
                
                // Step 2: Transition action: `ses_finalize_file(); ses_publish(SES_PUB_RECORDING_ABORTED);`.
                ses_finalize_file(); ses_publish(SES_PUB_RECORDING_ABORTED);
                
                // Step 3: Enter/move towards transition target `Idle`.
                IDLE_enter(sm);
                
                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for ROOT.<ChoicePoint>(CaptureResult)
        } // end of behavior for ROOT.<ChoicePoint>(OpenResult)
    } // end of behavior for Idle
    
    // No ancestor handles this event.
}

static void IDLE_stop(SessionSm* sm)
{
    // Idle behavior
    // uml: STOP / { ses_publish(SES_PUB_STOP_IGNORED); }
    {
        // Step 1: execute action `ses_publish(SES_PUB_STOP_IGNORED);`
        ses_publish(SES_PUB_STOP_IGNORED);
    } // end of behavior for Idle
    
    // No ancestor handles this event.
}

// Thread safe. This function can be disabled with `outputStateIdToStringFunction` setting.
char const * SessionSm_state_id_to_string(SessionSm_StateId id)
{
    switch (id)
    {
        case SessionSm_StateId_ROOT: return "ROOT";
        case SessionSm_StateId_ACTIVE: return "ACTIVE";
        case SessionSm_StateId_FINALIZING: return "FINALIZING";
        case SessionSm_StateId_RECORDING: return "RECORDING";
        case SessionSm_StateId_IDLE: return "IDLE";
        default: return "?";
    }
}

// Thread safe. This function can be disabled with `outputEventIdToStringFunction` setting.
char const * SessionSm_event_id_to_string(SessionSm_EventId id)
{
    switch (id)
    {
        case SessionSm_EventId_BLOCK_WRITTEN: return "BLOCK_WRITTEN";
        case SessionSm_EventId_CAPTURE_FAULT: return "CAPTURE_FAULT";
        case SessionSm_EventId_START: return "START";
        case SessionSm_EventId_STOP: return "STOP";
        default: return "?";
    }
}

// Returns the parent state for a given state. Returns ROOT if input has no parent.
// Thread safe. This function can be disabled with `outputGetParentIdFunction` setting.
SessionSm_StateId SessionSm_get_parent_id(SessionSm_StateId id)
{
    switch (id)
    {
        case SessionSm_StateId_ROOT: return SessionSm_StateId_ROOT;
        case SessionSm_StateId_ACTIVE: return SessionSm_StateId_ROOT;
        case SessionSm_StateId_FINALIZING: return SessionSm_StateId_ACTIVE;
        case SessionSm_StateId_RECORDING: return SessionSm_StateId_ACTIVE;
        case SessionSm_StateId_IDLE: return SessionSm_StateId_ROOT;
        default: return SessionSm_StateId_ROOT;
    }
}
