// Autogenerated with StateSmith 0.22.2+0c32be37bf4d4fee5499780a5ef37a7996c192f9.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

#ifndef SPOOKY_SESSION_SM_H
#define SPOOKY_SESSION_SM_H
#include <stdint.h>

typedef enum SessionSm_EventId
{
    SessionSm_EventId_BLOCK_WRITTEN = 0,
    SessionSm_EventId_CAPTURE_FAULT = 1,
    SessionSm_EventId_PREPARED = 2,
    SessionSm_EventId_START = 3,
    SessionSm_EventId_STOP = 4
} SessionSm_EventId;

#define SessionSm_EventIdCount (5)

typedef enum SessionSm_StateId
{
    SessionSm_StateId_ROOT = 0,
    SessionSm_StateId_ACTIVE = 1,
    SessionSm_StateId_FINALIZING = 2,
    SessionSm_StateId_PREPARING = 3,
    SessionSm_StateId_RECORDING = 4,
    SessionSm_StateId_IDLE = 5
} SessionSm_StateId;

#define SessionSm_StateIdCount (6)

// Subtree meta data generation can be disabled in settings.
// Details: https://github.com/StateSmith/StateSmith/issues/538
#define SessionSm_ROOT_SubtreeEndId (5)  // State 'SessionSm' subtree extends from itself (id: 0) to state 'Idle' (id: 5)
#define SessionSm_ACTIVE_SubtreeEndId (4)  // State 'Active' subtree extends from itself (id: 1) to state 'Recording' (id: 4)
#define SessionSm_FINALIZING_SubtreeEndId (2)  // State 'Finalizing' subtree extends from itself (id: 2) to state 'Finalizing' (id: 2)
#define SessionSm_PREPARING_SubtreeEndId (3)  // State 'Preparing' subtree extends from itself (id: 3) to state 'Preparing' (id: 3)
#define SessionSm_RECORDING_SubtreeEndId (4)  // State 'Recording' subtree extends from itself (id: 4) to state 'Recording' (id: 4)
#define SessionSm_IDLE_SubtreeEndId (5)  // State 'Idle' subtree extends from itself (id: 5) to state 'Idle' (id: 5)


// Generated state machine
// forward declaration
typedef struct SessionSm SessionSm;

// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void SessionSm_ctor(SessionSm* sm);

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void SessionSm_start(SessionSm* sm);

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void SessionSm_dispatch_event(SessionSm* sm, SessionSm_EventId event_id);

// Thread safe. This function can be disabled with `outputStateIdToStringFunction` setting.
char const * SessionSm_state_id_to_string(SessionSm_StateId id);

// Thread safe. This function can be disabled with `outputEventIdToStringFunction` setting.
char const * SessionSm_event_id_to_string(SessionSm_EventId id);

// Returns the parent state for a given state. Returns ROOT if input has no parent.
// Thread safe. This function can be disabled with `outputGetParentIdFunction` setting.
SessionSm_StateId SessionSm_get_parent_id(SessionSm_StateId id);

// Generated state machine
struct SessionSm
{
    // Used internally by state machine. Feel free to inspect, but don't modify.
    SessionSm_StateId state_id;
};

#endif // SPOOKY_SESSION_SM_H
